/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ActionLimitsReactionsPerAction from './ActionLimitsReactionsPerAction';

/**
 * The ActionLimitsReactions model module.
 * @module model/ActionLimitsReactions
 * @version 0.0.1
 */
class ActionLimitsReactions {
    /**
     * Constructs a new <code>ActionLimitsReactions</code>.
     * @alias module:model/ActionLimitsReactions
     */
    constructor() { 
        
        ActionLimitsReactions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActionLimitsReactions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionLimitsReactions} obj Optional instance to populate.
     * @return {module:model/ActionLimitsReactions} The populated <code>ActionLimitsReactions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionLimitsReactions();

            if (data.hasOwnProperty('perAction')) {
                obj['perAction'] = ActionLimitsReactionsPerAction.constructFromObject(data['perAction']);
            }
            if (data.hasOwnProperty('uniquePerAction')) {
                obj['uniquePerAction'] = ActionLimitsReactionsPerAction.constructFromObject(data['uniquePerAction']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ActionLimitsReactionsPerAction} perAction
 */
ActionLimitsReactions.prototype['perAction'] = undefined;

/**
 * @member {module:model/ActionLimitsReactionsPerAction} uniquePerAction
 */
ActionLimitsReactions.prototype['uniquePerAction'] = undefined;






export default ActionLimitsReactions;

