/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ActionDataBoard model module.
 * @module model/ActionDataBoard
 * @version 0.0.1
 */
class ActionDataBoard {
    /**
     * Constructs a new <code>ActionDataBoard</code>.
     * @alias module:model/ActionDataBoard
     */
    constructor() { 
        
        ActionDataBoard.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActionDataBoard</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionDataBoard} obj Optional instance to populate.
     * @return {module:model/ActionDataBoard} The populated <code>ActionDataBoard</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionDataBoard();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('shortLink')) {
                obj['shortLink'] = ApiClient.convertToType(data['shortLink'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ActionDataBoard.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ActionDataBoard.prototype['name'] = undefined;

/**
 * @member {String} shortLink
 */
ActionDataBoard.prototype['shortLink'] = undefined;






export default ActionDataBoard;

