/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ActionDisplayEntitiesCard model module.
 * @module model/ActionDisplayEntitiesCard
 * @version 0.0.1
 */
class ActionDisplayEntitiesCard {
    /**
     * Constructs a new <code>ActionDisplayEntitiesCard</code>.
     * @alias module:model/ActionDisplayEntitiesCard
     */
    constructor() { 
        
        ActionDisplayEntitiesCard.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActionDisplayEntitiesCard</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionDisplayEntitiesCard} obj Optional instance to populate.
     * @return {module:model/ActionDisplayEntitiesCard} The populated <code>ActionDisplayEntitiesCard</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionDisplayEntitiesCard();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('hideIfContext')) {
                obj['hideIfContext'] = ApiClient.convertToType(data['hideIfContext'], 'Boolean');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('shortLink')) {
                obj['shortLink'] = ApiClient.convertToType(data['shortLink'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
ActionDisplayEntitiesCard.prototype['type'] = undefined;

/**
 * @member {Boolean} hideIfContext
 */
ActionDisplayEntitiesCard.prototype['hideIfContext'] = undefined;

/**
 * @member {String} id
 */
ActionDisplayEntitiesCard.prototype['id'] = undefined;

/**
 * @member {String} shortLink
 */
ActionDisplayEntitiesCard.prototype['shortLink'] = undefined;

/**
 * @member {String} text
 */
ActionDisplayEntitiesCard.prototype['text'] = undefined;






export default ActionDisplayEntitiesCard;

