/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ActionDisplayEntitiesContextOn model module.
 * @module model/ActionDisplayEntitiesContextOn
 * @version 0.0.1
 */
class ActionDisplayEntitiesContextOn {
    /**
     * Constructs a new <code>ActionDisplayEntitiesContextOn</code>.
     * @alias module:model/ActionDisplayEntitiesContextOn
     */
    constructor() { 
        
        ActionDisplayEntitiesContextOn.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActionDisplayEntitiesContextOn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionDisplayEntitiesContextOn} obj Optional instance to populate.
     * @return {module:model/ActionDisplayEntitiesContextOn} The populated <code>ActionDisplayEntitiesContextOn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionDisplayEntitiesContextOn();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('translationKey')) {
                obj['translationKey'] = ApiClient.convertToType(data['translationKey'], 'String');
            }
            if (data.hasOwnProperty('hideIfContext')) {
                obj['hideIfContext'] = ApiClient.convertToType(data['hideIfContext'], 'Boolean');
            }
            if (data.hasOwnProperty('idContext')) {
                obj['idContext'] = ApiClient.convertToType(data['idContext'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
ActionDisplayEntitiesContextOn.prototype['type'] = undefined;

/**
 * @member {String} translationKey
 */
ActionDisplayEntitiesContextOn.prototype['translationKey'] = undefined;

/**
 * @member {Boolean} hideIfContext
 */
ActionDisplayEntitiesContextOn.prototype['hideIfContext'] = undefined;

/**
 * @member {String} idContext
 */
ActionDisplayEntitiesContextOn.prototype['idContext'] = undefined;






export default ActionDisplayEntitiesContextOn;

