/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ActionDisplayEntitiesComment model module.
 * @module model/ActionDisplayEntitiesComment
 * @version 0.0.1
 */
class ActionDisplayEntitiesComment {
    /**
     * Constructs a new <code>ActionDisplayEntitiesComment</code>.
     * @alias module:model/ActionDisplayEntitiesComment
     */
    constructor() { 
        
        ActionDisplayEntitiesComment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActionDisplayEntitiesComment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionDisplayEntitiesComment} obj Optional instance to populate.
     * @return {module:model/ActionDisplayEntitiesComment} The populated <code>ActionDisplayEntitiesComment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionDisplayEntitiesComment();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
ActionDisplayEntitiesComment.prototype['type'] = undefined;

/**
 * @member {String} text
 */
ActionDisplayEntitiesComment.prototype['text'] = undefined;






export default ActionDisplayEntitiesComment;

