/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ActionDataCard model module.
 * @module model/ActionDataCard
 * @version 0.0.1
 */
class ActionDataCard {
    /**
     * Constructs a new <code>ActionDataCard</code>.
     * @alias module:model/ActionDataCard
     */
    constructor() { 
        
        ActionDataCard.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActionDataCard</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionDataCard} obj Optional instance to populate.
     * @return {module:model/ActionDataCard} The populated <code>ActionDataCard</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionDataCard();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('idShort')) {
                obj['idShort'] = ApiClient.convertToType(data['idShort'], 'Number');
            }
            if (data.hasOwnProperty('shortLink')) {
                obj['shortLink'] = ApiClient.convertToType(data['shortLink'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ActionDataCard.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ActionDataCard.prototype['name'] = undefined;

/**
 * @member {Number} idShort
 */
ActionDataCard.prototype['idShort'] = undefined;

/**
 * @member {String} shortLink
 */
ActionDataCard.prototype['shortLink'] = undefined;






export default ActionDataCard;

