/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ActionDisplayEntitiesMemberCreator model module.
 * @module model/ActionDisplayEntitiesMemberCreator
 * @version 0.0.1
 */
class ActionDisplayEntitiesMemberCreator {
    /**
     * Constructs a new <code>ActionDisplayEntitiesMemberCreator</code>.
     * @alias module:model/ActionDisplayEntitiesMemberCreator
     */
    constructor() { 
        
        ActionDisplayEntitiesMemberCreator.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActionDisplayEntitiesMemberCreator</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionDisplayEntitiesMemberCreator} obj Optional instance to populate.
     * @return {module:model/ActionDisplayEntitiesMemberCreator} The populated <code>ActionDisplayEntitiesMemberCreator</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionDisplayEntitiesMemberCreator();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
ActionDisplayEntitiesMemberCreator.prototype['type'] = undefined;

/**
 * @member {String} id
 */
ActionDisplayEntitiesMemberCreator.prototype['id'] = undefined;

/**
 * @member {String} username
 */
ActionDisplayEntitiesMemberCreator.prototype['username'] = undefined;

/**
 * @member {String} text
 */
ActionDisplayEntitiesMemberCreator.prototype['text'] = undefined;






export default ActionDisplayEntitiesMemberCreator;

