/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ActionDisplayEntities from './ActionDisplayEntities';

/**
 * The ActionDisplay model module.
 * @module model/ActionDisplay
 * @version 0.0.1
 */
class ActionDisplay {
    /**
     * Constructs a new <code>ActionDisplay</code>.
     * @alias module:model/ActionDisplay
     */
    constructor() { 
        
        ActionDisplay.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActionDisplay</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionDisplay} obj Optional instance to populate.
     * @return {module:model/ActionDisplay} The populated <code>ActionDisplay</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionDisplay();

            if (data.hasOwnProperty('translationKey')) {
                obj['translationKey'] = ApiClient.convertToType(data['translationKey'], 'String');
            }
            if (data.hasOwnProperty('entities')) {
                obj['entities'] = ActionDisplayEntities.constructFromObject(data['entities']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} translationKey
 */
ActionDisplay.prototype['translationKey'] = undefined;

/**
 * @member {module:model/ActionDisplayEntities} entities
 */
ActionDisplay.prototype['entities'] = undefined;






export default ActionDisplay;

