/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ActionLimitsReactions from './ActionLimitsReactions';

/**
 * The ActionLimits model module.
 * @module model/ActionLimits
 * @version 0.0.1
 */
class ActionLimits {
    /**
     * Constructs a new <code>ActionLimits</code>.
     * @alias module:model/ActionLimits
     */
    constructor() { 
        
        ActionLimits.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActionLimits</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionLimits} obj Optional instance to populate.
     * @return {module:model/ActionLimits} The populated <code>ActionLimits</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionLimits();

            if (data.hasOwnProperty('reactions')) {
                obj['reactions'] = ActionLimitsReactions.constructFromObject(data['reactions']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ActionLimitsReactions} reactions
 */
ActionLimits.prototype['reactions'] = undefined;






export default ActionLimits;

