/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AttachmentFields.
* @enum {}
* @readonly
*/
export default class AttachmentFields {
    
        /**
         * value: "id"
         * @const
         */
        "id" = "id";

    
        /**
         * value: "bytes"
         * @const
         */
        "bytes" = "bytes";

    
        /**
         * value: "date"
         * @const
         */
        "date" = "date";

    
        /**
         * value: "edgeColor"
         * @const
         */
        "edgeColor" = "edgeColor";

    
        /**
         * value: "idMember"
         * @const
         */
        "idMember" = "idMember";

    
        /**
         * value: "isUpload"
         * @const
         */
        "isUpload" = "isUpload";

    
        /**
         * value: "mimeType"
         * @const
         */
        "mimeType" = "mimeType";

    
        /**
         * value: "name"
         * @const
         */
        "name" = "name";

    
        /**
         * value: "previews"
         * @const
         */
        "previews" = "previews";

    
        /**
         * value: "url"
         * @const
         */
        "url" = "url";

    
        /**
         * value: "pos"
         * @const
         */
        "pos" = "pos";

    

    /**
    * Returns a <code>AttachmentFields</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AttachmentFields} The enum <code>AttachmentFields</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

