/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BoardBackground model module.
 * @module model/BoardBackground
 * @version 0.0.1
 */
class BoardBackground {
    /**
     * Constructs a new <code>BoardBackground</code>.
     * @alias module:model/BoardBackground
     */
    constructor() { 
        
        BoardBackground.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BoardBackground</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BoardBackground} obj Optional instance to populate.
     * @return {module:model/BoardBackground} The populated <code>BoardBackground</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BoardBackground();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
BoardBackground.prototype['id'] = undefined;






export default BoardBackground;

