/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class BoardFields.
* @enum {}
* @readonly
*/
export default class BoardFields {
    
        /**
         * value: "id"
         * @const
         */
        "id" = "id";

    
        /**
         * value: "name"
         * @const
         */
        "name" = "name";

    
        /**
         * value: "desc"
         * @const
         */
        "desc" = "desc";

    
        /**
         * value: "descData"
         * @const
         */
        "descData" = "descData";

    
        /**
         * value: "closed"
         * @const
         */
        "closed" = "closed";

    
        /**
         * value: "idMemberCreator"
         * @const
         */
        "idMemberCreator" = "idMemberCreator";

    
        /**
         * value: "idOrganization"
         * @const
         */
        "idOrganization" = "idOrganization";

    
        /**
         * value: "pinned"
         * @const
         */
        "pinned" = "pinned";

    
        /**
         * value: "url"
         * @const
         */
        "url" = "url";

    
        /**
         * value: "shortUrl"
         * @const
         */
        "shortUrl" = "shortUrl";

    
        /**
         * value: "prefs"
         * @const
         */
        "prefs" = "prefs";

    
        /**
         * value: "labelNames"
         * @const
         */
        "labelNames" = "labelNames";

    
        /**
         * value: "starred"
         * @const
         */
        "starred" = "starred";

    
        /**
         * value: "limits"
         * @const
         */
        "limits" = "limits";

    
        /**
         * value: "memberships"
         * @const
         */
        "memberships" = "memberships";

    
        /**
         * value: "enterpriseOwned"
         * @const
         */
        "enterpriseOwned" = "enterpriseOwned";

    

    /**
    * Returns a <code>BoardFields</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/BoardFields} The enum <code>BoardFields</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

