/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BoardLabelNames from './BoardLabelNames';
import Limits from './Limits';
import Prefs from './Prefs';

/**
 * The Board model module.
 * @module model/Board
 * @version 0.0.1
 */
class Board {
    /**
     * Constructs a new <code>Board</code>.
     * @alias module:model/Board
     * @param id {String} 
     */
    constructor(id) { 
        
        Board.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>Board</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Board} obj Optional instance to populate.
     * @return {module:model/Board} The populated <code>Board</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Board();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('desc')) {
                obj['desc'] = ApiClient.convertToType(data['desc'], 'String');
            }
            if (data.hasOwnProperty('descData')) {
                obj['descData'] = ApiClient.convertToType(data['descData'], 'String');
            }
            if (data.hasOwnProperty('closed')) {
                obj['closed'] = ApiClient.convertToType(data['closed'], 'Boolean');
            }
            if (data.hasOwnProperty('idMemberCreator')) {
                obj['idMemberCreator'] = ApiClient.convertToType(data['idMemberCreator'], 'String');
            }
            if (data.hasOwnProperty('idOrganization')) {
                obj['idOrganization'] = ApiClient.convertToType(data['idOrganization'], 'String');
            }
            if (data.hasOwnProperty('pinned')) {
                obj['pinned'] = ApiClient.convertToType(data['pinned'], 'Boolean');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('shortUrl')) {
                obj['shortUrl'] = ApiClient.convertToType(data['shortUrl'], 'String');
            }
            if (data.hasOwnProperty('prefs')) {
                obj['prefs'] = Prefs.constructFromObject(data['prefs']);
            }
            if (data.hasOwnProperty('labelNames')) {
                obj['labelNames'] = BoardLabelNames.constructFromObject(data['labelNames']);
            }
            if (data.hasOwnProperty('limits')) {
                obj['limits'] = Limits.constructFromObject(data['limits']);
            }
            if (data.hasOwnProperty('starred')) {
                obj['starred'] = ApiClient.convertToType(data['starred'], 'Boolean');
            }
            if (data.hasOwnProperty('memberships')) {
                obj['memberships'] = ApiClient.convertToType(data['memberships'], 'String');
            }
            if (data.hasOwnProperty('shortLink')) {
                obj['shortLink'] = ApiClient.convertToType(data['shortLink'], 'String');
            }
            if (data.hasOwnProperty('subscribed')) {
                obj['subscribed'] = ApiClient.convertToType(data['subscribed'], 'Boolean');
            }
            if (data.hasOwnProperty('powerUps')) {
                obj['powerUps'] = ApiClient.convertToType(data['powerUps'], 'String');
            }
            if (data.hasOwnProperty('dateLastActivity')) {
                obj['dateLastActivity'] = ApiClient.convertToType(data['dateLastActivity'], 'Date');
            }
            if (data.hasOwnProperty('dateLastView')) {
                obj['dateLastView'] = ApiClient.convertToType(data['dateLastView'], 'Date');
            }
            if (data.hasOwnProperty('idTags')) {
                obj['idTags'] = ApiClient.convertToType(data['idTags'], 'String');
            }
            if (data.hasOwnProperty('datePluginDisable')) {
                obj['datePluginDisable'] = ApiClient.convertToType(data['datePluginDisable'], 'Date');
            }
            if (data.hasOwnProperty('creationMethod')) {
                obj['creationMethod'] = ApiClient.convertToType(data['creationMethod'], 'String');
            }
            if (data.hasOwnProperty('ixUpdate')) {
                obj['ixUpdate'] = ApiClient.convertToType(data['ixUpdate'], 'Number');
            }
            if (data.hasOwnProperty('templateGallery')) {
                obj['templateGallery'] = ApiClient.convertToType(data['templateGallery'], 'String');
            }
            if (data.hasOwnProperty('enterpriseOwned')) {
                obj['enterpriseOwned'] = ApiClient.convertToType(data['enterpriseOwned'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Board.prototype['id'] = undefined;

/**
 * @member {String} desc
 */
Board.prototype['desc'] = undefined;

/**
 * @member {String} descData
 */
Board.prototype['descData'] = undefined;

/**
 * @member {Boolean} closed
 */
Board.prototype['closed'] = undefined;

/**
 * @member {String} idMemberCreator
 */
Board.prototype['idMemberCreator'] = undefined;

/**
 * @member {String} idOrganization
 */
Board.prototype['idOrganization'] = undefined;

/**
 * @member {Boolean} pinned
 */
Board.prototype['pinned'] = undefined;

/**
 * @member {String} url
 */
Board.prototype['url'] = undefined;

/**
 * @member {String} shortUrl
 */
Board.prototype['shortUrl'] = undefined;

/**
 * @member {module:model/Prefs} prefs
 */
Board.prototype['prefs'] = undefined;

/**
 * @member {module:model/BoardLabelNames} labelNames
 */
Board.prototype['labelNames'] = undefined;

/**
 * @member {module:model/Limits} limits
 */
Board.prototype['limits'] = undefined;

/**
 * @member {Boolean} starred
 */
Board.prototype['starred'] = undefined;

/**
 * @member {String} memberships
 */
Board.prototype['memberships'] = undefined;

/**
 * @member {String} shortLink
 */
Board.prototype['shortLink'] = undefined;

/**
 * @member {Boolean} subscribed
 */
Board.prototype['subscribed'] = undefined;

/**
 * @member {String} powerUps
 */
Board.prototype['powerUps'] = undefined;

/**
 * @member {Date} dateLastActivity
 */
Board.prototype['dateLastActivity'] = undefined;

/**
 * @member {Date} dateLastView
 */
Board.prototype['dateLastView'] = undefined;

/**
 * @member {String} idTags
 */
Board.prototype['idTags'] = undefined;

/**
 * @member {Date} datePluginDisable
 */
Board.prototype['datePluginDisable'] = undefined;

/**
 * @member {String} creationMethod
 */
Board.prototype['creationMethod'] = undefined;

/**
 * @member {Number} ixUpdate
 */
Board.prototype['ixUpdate'] = undefined;

/**
 * @member {String} templateGallery
 */
Board.prototype['templateGallery'] = undefined;

/**
 * @member {Boolean} enterpriseOwned
 */
Board.prototype['enterpriseOwned'] = undefined;






export default Board;

