/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CardBadgesAttachmentsByTypeTrello model module.
 * @module model/CardBadgesAttachmentsByTypeTrello
 * @version 0.0.1
 */
class CardBadgesAttachmentsByTypeTrello {
    /**
     * Constructs a new <code>CardBadgesAttachmentsByTypeTrello</code>.
     * @alias module:model/CardBadgesAttachmentsByTypeTrello
     */
    constructor() { 
        
        CardBadgesAttachmentsByTypeTrello.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CardBadgesAttachmentsByTypeTrello</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CardBadgesAttachmentsByTypeTrello} obj Optional instance to populate.
     * @return {module:model/CardBadgesAttachmentsByTypeTrello} The populated <code>CardBadgesAttachmentsByTypeTrello</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CardBadgesAttachmentsByTypeTrello();

            if (data.hasOwnProperty('board')) {
                obj['board'] = ApiClient.convertToType(data['board'], 'Number');
            }
            if (data.hasOwnProperty('card')) {
                obj['card'] = ApiClient.convertToType(data['card'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} board
 */
CardBadgesAttachmentsByTypeTrello.prototype['board'] = undefined;

/**
 * @member {Number} card
 */
CardBadgesAttachmentsByTypeTrello.prototype['card'] = undefined;






export default CardBadgesAttachmentsByTypeTrello;

