/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class CardFields.
* @enum {}
* @readonly
*/
export default class CardFields {
    
        /**
         * value: "id"
         * @const
         */
        "id" = "id";

    
        /**
         * value: "address"
         * @const
         */
        "address" = "address";

    
        /**
         * value: "badges"
         * @const
         */
        "badges" = "badges";

    
        /**
         * value: "checkItemStates"
         * @const
         */
        "checkItemStates" = "checkItemStates";

    
        /**
         * value: "closed"
         * @const
         */
        "closed" = "closed";

    
        /**
         * value: "coordinates"
         * @const
         */
        "coordinates" = "coordinates";

    
        /**
         * value: "creationMethod"
         * @const
         */
        "creationMethod" = "creationMethod";

    
        /**
         * value: "dueComplete"
         * @const
         */
        "dueComplete" = "dueComplete";

    
        /**
         * value: "dateLastActivity"
         * @const
         */
        "dateLastActivity" = "dateLastActivity";

    
        /**
         * value: "desc"
         * @const
         */
        "desc" = "desc";

    
        /**
         * value: "descData"
         * @const
         */
        "descData" = "descData";

    
        /**
         * value: "due"
         * @const
         */
        "due" = "due";

    
        /**
         * value: "dueReminder"
         * @const
         */
        "dueReminder" = "dueReminder";

    
        /**
         * value: "email"
         * @const
         */
        "email" = "email";

    
        /**
         * value: "idBoard"
         * @const
         */
        "idBoard" = "idBoard";

    
        /**
         * value: "idChecklists"
         * @const
         */
        "idChecklists" = "idChecklists";

    
        /**
         * value: "idLabels"
         * @const
         */
        "idLabels" = "idLabels";

    
        /**
         * value: "idList"
         * @const
         */
        "idList" = "idList";

    
        /**
         * value: "idMembers"
         * @const
         */
        "idMembers" = "idMembers";

    
        /**
         * value: "idMembersVoted"
         * @const
         */
        "idMembersVoted" = "idMembersVoted";

    
        /**
         * value: "idShort"
         * @const
         */
        "idShort" = "idShort";

    
        /**
         * value: "idAttachmentCover"
         * @const
         */
        "idAttachmentCover" = "idAttachmentCover";

    
        /**
         * value: "labels"
         * @const
         */
        "labels" = "labels";

    
        /**
         * value: "limits"
         * @const
         */
        "limits" = "limits";

    
        /**
         * value: "locationName"
         * @const
         */
        "locationName" = "locationName";

    
        /**
         * value: "manualCoverAttachment"
         * @const
         */
        "manualCoverAttachment" = "manualCoverAttachment";

    
        /**
         * value: "name"
         * @const
         */
        "name" = "name";

    
        /**
         * value: "pos"
         * @const
         */
        "pos" = "pos";

    
        /**
         * value: "shortLink"
         * @const
         */
        "shortLink" = "shortLink";

    
        /**
         * value: "shortUrl"
         * @const
         */
        "shortUrl" = "shortUrl";

    
        /**
         * value: "subscribed"
         * @const
         */
        "subscribed" = "subscribed";

    
        /**
         * value: "url"
         * @const
         */
        "url" = "url";

    
        /**
         * value: "cover"
         * @const
         */
        "cover" = "cover";

    
        /**
         * value: "isTemplate"
         * @const
         */
        "isTemplate" = "isTemplate";

    

    /**
    * Returns a <code>CardFields</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/CardFields} The enum <code>CardFields</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

