/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CardBadgesAttachmentsByTypeTrello from './CardBadgesAttachmentsByTypeTrello';

/**
 * The CardBadgesAttachmentsByType model module.
 * @module model/CardBadgesAttachmentsByType
 * @version 0.0.1
 */
class CardBadgesAttachmentsByType {
    /**
     * Constructs a new <code>CardBadgesAttachmentsByType</code>.
     * @alias module:model/CardBadgesAttachmentsByType
     */
    constructor() { 
        
        CardBadgesAttachmentsByType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CardBadgesAttachmentsByType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CardBadgesAttachmentsByType} obj Optional instance to populate.
     * @return {module:model/CardBadgesAttachmentsByType} The populated <code>CardBadgesAttachmentsByType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CardBadgesAttachmentsByType();

            if (data.hasOwnProperty('trello')) {
                obj['trello'] = CardBadgesAttachmentsByTypeTrello.constructFromObject(data['trello']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CardBadgesAttachmentsByTypeTrello} trello
 */
CardBadgesAttachmentsByType.prototype['trello'] = undefined;






export default CardBadgesAttachmentsByType;

