/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CFValue model module.
 * @module model/CFValue
 * @version 0.0.1
 */
class CFValue {
    /**
     * Constructs a new <code>CFValue</code>.
     * @alias module:model/CFValue
     */
    constructor() { 
        
        CFValue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CFValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CFValue} obj Optional instance to populate.
     * @return {module:model/CFValue} The populated <code>CFValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CFValue();

            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} number
 */
CFValue.prototype['number'] = undefined;






export default CFValue;

