/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CheckItem model module.
 * @module model/CheckItem
 * @version 0.0.1
 */
class CheckItem {
    /**
     * Constructs a new <code>CheckItem</code>.
     * @alias module:model/CheckItem
     */
    constructor() { 
        
        CheckItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CheckItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CheckItem} obj Optional instance to populate.
     * @return {module:model/CheckItem} The populated <code>CheckItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckItem();

            if (data.hasOwnProperty('idChecklist')) {
                obj['idChecklist'] = ApiClient.convertToType(data['idChecklist'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('nameData')) {
                obj['nameData'] = ApiClient.convertToType(data['nameData'], 'String');
            }
            if (data.hasOwnProperty('pos')) {
                obj['pos'] = ApiClient.convertToType(data['pos'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} idChecklist
 */
CheckItem.prototype['idChecklist'] = undefined;

/**
 * @member {module:model/CheckItem.StateEnum} state
 */
CheckItem.prototype['state'] = undefined;

/**
 * @member {String} id
 */
CheckItem.prototype['id'] = undefined;

/**
 * @member {String} name
 */
CheckItem.prototype['name'] = undefined;

/**
 * @member {String} nameData
 */
CheckItem.prototype['nameData'] = undefined;

/**
 * @member {String} pos
 */
CheckItem.prototype['pos'] = undefined;





/**
 * Allowed values for the <code>state</code> property.
 * @enum {String}
 * @readonly
 */
CheckItem['StateEnum'] = {

    /**
     * value: "complete"
     * @const
     */
    "complete": "complete",

    /**
     * value: "incomplete"
     * @const
     */
    "incomplete": "incomplete"
};



export default CheckItem;

