/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Color.
* @enum {}
* @readonly
*/
export default class Color {
    
        /**
         * value: "yellow"
         * @const
         */
        "yellow" = "yellow";

    
        /**
         * value: "purple"
         * @const
         */
        "purple" = "purple";

    
        /**
         * value: "blue"
         * @const
         */
        "blue" = "blue";

    
        /**
         * value: "red"
         * @const
         */
        "red" = "red";

    
        /**
         * value: "green"
         * @const
         */
        "green" = "green";

    
        /**
         * value: "orange"
         * @const
         */
        "orange" = "orange";

    
        /**
         * value: "black"
         * @const
         */
        "black" = "black";

    
        /**
         * value: "sky"
         * @const
         */
        "sky" = "sky";

    
        /**
         * value: "pink"
         * @const
         */
        "pink" = "pink";

    
        /**
         * value: "lime"
         * @const
         */
        "lime" = "lime";

    

    /**
    * Returns a <code>Color</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Color} The enum <code>Color</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

