/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CardsIdValue from './CardsIdValue';

/**
 * The Cover model module.
 * @module model/Cover
 * @version 0.0.1
 */
class Cover {
    /**
     * Constructs a new <code>Cover</code>.
     * @alias module:model/Cover
     */
    constructor() { 
        
        Cover.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Cover</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Cover} obj Optional instance to populate.
     * @return {module:model/Cover} The populated <code>Cover</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Cover();

            if (data.hasOwnProperty('value')) {
                obj['value'] = CardsIdValue.constructFromObject(data['value']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CardsIdValue} value
 */
Cover.prototype['value'] = undefined;






export default Cover;

