/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CustomStickerScaled from './CustomStickerScaled';

/**
 * The CustomSticker model module.
 * @module model/CustomSticker
 * @version 0.0.1
 */
class CustomSticker {
    /**
     * Constructs a new <code>CustomSticker</code>.
     * @alias module:model/CustomSticker
     */
    constructor() { 
        
        CustomSticker.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomSticker</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomSticker} obj Optional instance to populate.
     * @return {module:model/CustomSticker} The populated <code>CustomSticker</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomSticker();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('scaled')) {
                obj['scaled'] = ApiClient.convertToType(data['scaled'], [CustomStickerScaled]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
CustomSticker.prototype['id'] = undefined;

/**
 * @member {String} url
 */
CustomSticker.prototype['url'] = undefined;

/**
 * @member {Array.<module:model/CustomStickerScaled>} scaled
 */
CustomSticker.prototype['scaled'] = undefined;






export default CustomSticker;

