/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CustomFieldDisplay from './CustomFieldDisplay';

/**
 * The CustomField model module.
 * @module model/CustomField
 * @version 0.0.1
 */
class CustomField {
    /**
     * Constructs a new <code>CustomField</code>.
     * @alias module:model/CustomField
     */
    constructor() { 
        
        CustomField.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomField</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomField} obj Optional instance to populate.
     * @return {module:model/CustomField} The populated <code>CustomField</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomField();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('idModel')) {
                obj['idModel'] = ApiClient.convertToType(data['idModel'], 'String');
            }
            if (data.hasOwnProperty('modelType')) {
                obj['modelType'] = ApiClient.convertToType(data['modelType'], 'String');
            }
            if (data.hasOwnProperty('fieldGroup')) {
                obj['fieldGroup'] = ApiClient.convertToType(data['fieldGroup'], 'String');
            }
            if (data.hasOwnProperty('display')) {
                obj['display'] = CustomFieldDisplay.constructFromObject(data['display']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
CustomField.prototype['id'] = undefined;

/**
 * @member {String} idModel
 */
CustomField.prototype['idModel'] = undefined;

/**
 * @member {module:model/CustomField.ModelTypeEnum} modelType
 */
CustomField.prototype['modelType'] = undefined;

/**
 * @member {String} fieldGroup
 */
CustomField.prototype['fieldGroup'] = undefined;

/**
 * @member {module:model/CustomFieldDisplay} display
 */
CustomField.prototype['display'] = undefined;

/**
 * @member {String} type
 */
CustomField.prototype['type'] = undefined;





/**
 * Allowed values for the <code>modelType</code> property.
 * @enum {String}
 * @readonly
 */
CustomField['ModelTypeEnum'] = {

    /**
     * value: "card"
     * @const
     */
    "card": "card",

    /**
     * value: "board"
     * @const
     */
    "board": "board",

    /**
     * value: "member"
     * @const
     */
    "member": "member"
};



export default CustomField;

