/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CustomFieldDisplayOptions from './CustomFieldDisplayOptions';

/**
 * The CustomFieldDisplay model module.
 * @module model/CustomFieldDisplay
 * @version 0.0.1
 */
class CustomFieldDisplay {
    /**
     * Constructs a new <code>CustomFieldDisplay</code>.
     * @alias module:model/CustomFieldDisplay
     */
    constructor() { 
        
        CustomFieldDisplay.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomFieldDisplay</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomFieldDisplay} obj Optional instance to populate.
     * @return {module:model/CustomFieldDisplay} The populated <code>CustomFieldDisplay</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomFieldDisplay();

            if (data.hasOwnProperty('cardFront')) {
                obj['cardFront'] = ApiClient.convertToType(data['cardFront'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('pos')) {
                obj['pos'] = ApiClient.convertToType(data['pos'], 'String');
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], [CustomFieldDisplayOptions]);
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} cardFront
 */
CustomFieldDisplay.prototype['cardFront'] = undefined;

/**
 * @member {String} name
 */
CustomFieldDisplay.prototype['name'] = undefined;

/**
 * @member {String} pos
 */
CustomFieldDisplay.prototype['pos'] = undefined;

/**
 * @member {Array.<module:model/CustomFieldDisplayOptions>} options
 */
CustomFieldDisplay.prototype['options'] = undefined;






export default CustomFieldDisplay;

