/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CustomFieldItemsValue from './CustomFieldItemsValue';

/**
 * The CustomFieldItems model module.
 * @module model/CustomFieldItems
 * @version 0.0.1
 */
class CustomFieldItems {
    /**
     * Constructs a new <code>CustomFieldItems</code>.
     * @alias module:model/CustomFieldItems
     */
    constructor() { 
        
        CustomFieldItems.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomFieldItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomFieldItems} obj Optional instance to populate.
     * @return {module:model/CustomFieldItems} The populated <code>CustomFieldItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomFieldItems();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = CustomFieldItemsValue.constructFromObject(data['value']);
            }
            if (data.hasOwnProperty('idCustomField')) {
                obj['idCustomField'] = ApiClient.convertToType(data['idCustomField'], 'String');
            }
            if (data.hasOwnProperty('idModel')) {
                obj['idModel'] = ApiClient.convertToType(data['idModel'], 'String');
            }
            if (data.hasOwnProperty('modelType')) {
                obj['modelType'] = ApiClient.convertToType(data['modelType'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
CustomFieldItems.prototype['id'] = undefined;

/**
 * @member {module:model/CustomFieldItemsValue} value
 */
CustomFieldItems.prototype['value'] = undefined;

/**
 * @member {String} idCustomField
 */
CustomFieldItems.prototype['idCustomField'] = undefined;

/**
 * @member {String} idModel
 */
CustomFieldItems.prototype['idModel'] = undefined;

/**
 * @member {module:model/CustomFieldItems.ModelTypeEnum} modelType
 */
CustomFieldItems.prototype['modelType'] = undefined;





/**
 * Allowed values for the <code>modelType</code> property.
 * @enum {String}
 * @readonly
 */
CustomFieldItems['ModelTypeEnum'] = {

    /**
     * value: "card"
     * @const
     */
    "card": "card",

    /**
     * value: "board"
     * @const
     */
    "board": "board",

    /**
     * value: "member"
     * @const
     */
    "member": "member"
};



export default CustomFieldItems;

