/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EmojiTrello from './EmojiTrello';

/**
 * The Emoji model module.
 * @module model/Emoji
 * @version 0.0.1
 */
class Emoji {
    /**
     * Constructs a new <code>Emoji</code>.
     * @alias module:model/Emoji
     */
    constructor() { 
        
        Emoji.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Emoji</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Emoji} obj Optional instance to populate.
     * @return {module:model/Emoji} The populated <code>Emoji</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Emoji();

            if (data.hasOwnProperty('trello')) {
                obj['trello'] = ApiClient.convertToType(data['trello'], [EmojiTrello]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/EmojiTrello>} trello
 */
Emoji.prototype['trello'] = undefined;






export default Emoji;

