/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EnterprisePrefsSignup from './EnterprisePrefsSignup';

/**
 * The EnterprisePrefs model module.
 * @module model/EnterprisePrefs
 * @version 0.0.1
 */
class EnterprisePrefs {
    /**
     * Constructs a new <code>EnterprisePrefs</code>.
     * @alias module:model/EnterprisePrefs
     */
    constructor() { 
        
        EnterprisePrefs.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EnterprisePrefs</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EnterprisePrefs} obj Optional instance to populate.
     * @return {module:model/EnterprisePrefs} The populated <code>EnterprisePrefs</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EnterprisePrefs();

            if (data.hasOwnProperty('ssoOnly')) {
                obj['ssoOnly'] = ApiClient.convertToType(data['ssoOnly'], 'Boolean');
            }
            if (data.hasOwnProperty('signup')) {
                obj['signup'] = EnterprisePrefsSignup.constructFromObject(data['signup']);
            }
            if (data.hasOwnProperty('mandatoryTransferDate')) {
                obj['mandatoryTransferDate'] = ApiClient.convertToType(data['mandatoryTransferDate'], 'Date');
            }
            if (data.hasOwnProperty('brandingColor')) {
                obj['brandingColor'] = ApiClient.convertToType(data['brandingColor'], 'String');
            }
            if (data.hasOwnProperty('autoJoinOrganizations')) {
                obj['autoJoinOrganizations'] = ApiClient.convertToType(data['autoJoinOrganizations'], 'Boolean');
            }
            if (data.hasOwnProperty('notifications')) {
                obj['notifications'] = ApiClient.convertToType(data['notifications'], Object);
            }
            if (data.hasOwnProperty('maxMembers')) {
                obj['maxMembers'] = ApiClient.convertToType(data['maxMembers'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} ssoOnly
 */
EnterprisePrefs.prototype['ssoOnly'] = undefined;

/**
 * @member {module:model/EnterprisePrefsSignup} signup
 */
EnterprisePrefs.prototype['signup'] = undefined;

/**
 * @member {Date} mandatoryTransferDate
 */
EnterprisePrefs.prototype['mandatoryTransferDate'] = undefined;

/**
 * @member {String} brandingColor
 */
EnterprisePrefs.prototype['brandingColor'] = undefined;

/**
 * @member {Boolean} autoJoinOrganizations
 */
EnterprisePrefs.prototype['autoJoinOrganizations'] = undefined;

/**
 * @member {Object} notifications
 */
EnterprisePrefs.prototype['notifications'] = undefined;

/**
 * @member {Number} maxMembers
 */
EnterprisePrefs.prototype['maxMembers'] = undefined;






export default EnterprisePrefs;

