/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AnyOfstring from './AnyOfstring';

/**
 * The EnterpriseOrganizationPrefs model module.
 * @module model/EnterpriseOrganizationPrefs
 * @version 0.0.1
 */
class EnterpriseOrganizationPrefs {
    /**
     * Constructs a new <code>EnterpriseOrganizationPrefs</code>.
     * @alias module:model/EnterpriseOrganizationPrefs
     */
    constructor() { 
        
        EnterpriseOrganizationPrefs.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EnterpriseOrganizationPrefs</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EnterpriseOrganizationPrefs} obj Optional instance to populate.
     * @return {module:model/EnterpriseOrganizationPrefs} The populated <code>EnterpriseOrganizationPrefs</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EnterpriseOrganizationPrefs();

            if (data.hasOwnProperty('boardVisibilityRestrict')) {
                obj['boardVisibilityRestrict'] = ApiClient.convertToType(data['boardVisibilityRestrict'], Object);
            }
            if (data.hasOwnProperty('boardDeleteRestrict')) {
                obj['boardDeleteRestrict'] = ApiClient.convertToType(data['boardDeleteRestrict'], Object);
            }
            if (data.hasOwnProperty('attachmentRestrictions')) {
                obj['attachmentRestrictions'] = ApiClient.convertToType(data['attachmentRestrictions'], [AnyOfstring]);
            }
        }
        return obj;
    }


}

/**
 * @member {Object} boardVisibilityRestrict
 */
EnterpriseOrganizationPrefs.prototype['boardVisibilityRestrict'] = undefined;

/**
 * @member {Object} boardDeleteRestrict
 */
EnterpriseOrganizationPrefs.prototype['boardDeleteRestrict'] = undefined;

/**
 * @member {Array.<module:model/AnyOfstring>} attachmentRestrictions
 */
EnterpriseOrganizationPrefs.prototype['attachmentRestrictions'] = undefined;






export default EnterpriseOrganizationPrefs;

