/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EnterprisePrefsSignup model module.
 * @module model/EnterprisePrefsSignup
 * @version 0.0.1
 */
class EnterprisePrefsSignup {
    /**
     * Constructs a new <code>EnterprisePrefsSignup</code>.
     * @alias module:model/EnterprisePrefsSignup
     */
    constructor() { 
        
        EnterprisePrefsSignup.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EnterprisePrefsSignup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EnterprisePrefsSignup} obj Optional instance to populate.
     * @return {module:model/EnterprisePrefsSignup} The populated <code>EnterprisePrefsSignup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EnterprisePrefsSignup();

            if (data.hasOwnProperty('banner')) {
                obj['banner'] = ApiClient.convertToType(data['banner'], 'String');
            }
            if (data.hasOwnProperty('bannerHtml')) {
                obj['bannerHtml'] = ApiClient.convertToType(data['bannerHtml'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} banner
 */
EnterprisePrefsSignup.prototype['banner'] = undefined;

/**
 * @member {String} bannerHtml
 */
EnterprisePrefsSignup.prototype['bannerHtml'] = undefined;






export default EnterprisePrefsSignup;

