/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExportStatus model module.
 * @module model/ExportStatus
 * @version 0.0.1
 */
class ExportStatus {
    /**
     * Constructs a new <code>ExportStatus</code>.
     * @alias module:model/ExportStatus
     */
    constructor() { 
        
        ExportStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExportStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExportStatus} obj Optional instance to populate.
     * @return {module:model/ExportStatus} The populated <code>ExportStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExportStatus();

            if (data.hasOwnProperty('attempts')) {
                obj['attempts'] = ApiClient.convertToType(data['attempts'], 'Number');
            }
            if (data.hasOwnProperty('finished')) {
                obj['finished'] = ApiClient.convertToType(data['finished'], 'Boolean');
            }
            if (data.hasOwnProperty('stage')) {
                obj['stage'] = ApiClient.convertToType(data['stage'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} attempts
 */
ExportStatus.prototype['attempts'] = undefined;

/**
 * @member {Boolean} finished
 */
ExportStatus.prototype['finished'] = undefined;

/**
 * @member {String} stage
 */
ExportStatus.prototype['stage'] = undefined;






export default ExportStatus;

