/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject model module.
 * @module model/InlineObject
 * @version 0.0.1
 */
class InlineObject {
    /**
     * Constructs a new <code>InlineObject</code>.
     * @alias module:model/InlineObject
     */
    constructor() { 
        
        InlineObject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject} obj Optional instance to populate.
     * @return {module:model/InlineObject} The populated <code>InlineObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject();

            if (data.hasOwnProperty('shortName')) {
                obj['shortName'] = ApiClient.convertToType(data['shortName'], 'String');
            }
            if (data.hasOwnProperty('skinVariation')) {
                obj['skinVariation'] = ApiClient.convertToType(data['skinVariation'], 'String');
            }
            if (data.hasOwnProperty('native')) {
                obj['native'] = ApiClient.convertToType(data['native'], 'String');
            }
            if (data.hasOwnProperty('unified')) {
                obj['unified'] = ApiClient.convertToType(data['unified'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The primary `shortName` of the emoji to add. See [/emoji](#emoji)
 * @member {String} shortName
 */
InlineObject.prototype['shortName'] = undefined;

/**
 * The `skinVariation` of the emoji to add. See [/emoji](#emoji)
 * @member {String} skinVariation
 */
InlineObject.prototype['skinVariation'] = undefined;

/**
 * The emoji to add as a native unicode emoji. See [/emoji](#emoji)
 * @member {String} native
 */
InlineObject.prototype['native'] = undefined;

/**
 * The `unified` value of the emoji to add. See [/emoji](#emoji)
 * @member {String} unified
 */
InlineObject.prototype['unified'] = undefined;






export default InlineObject;

