/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PosStringOrNumber from './PosStringOrNumber';

/**
 * The InlineObject3 model module.
 * @module model/InlineObject3
 * @version 0.0.1
 */
class InlineObject3 {
    /**
     * Constructs a new <code>InlineObject3</code>.
     * @alias module:model/InlineObject3
     */
    constructor() { 
        
        InlineObject3.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject3</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject3} obj Optional instance to populate.
     * @return {module:model/InlineObject3} The populated <code>InlineObject3</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject3();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('pos')) {
                obj['pos'] = PosStringOrNumber.constructFromObject(data['pos']);
            }
            if (data.hasOwnProperty('display/cardFront')) {
                obj['display/cardFront'] = ApiClient.convertToType(data['display/cardFront'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * The name of the Custom Field
 * @member {String} name
 */
InlineObject3.prototype['name'] = undefined;

/**
 * @member {module:model/PosStringOrNumber} pos
 */
InlineObject3.prototype['pos'] = undefined;

/**
 * Whether to display this custom field on the front of cards
 * @member {Boolean} display/cardFront
 */
InlineObject3.prototype['display/cardFront'] = undefined;






export default InlineObject3;

