/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LimitsObject from './LimitsObject';

/**
 * The LimitsAttachments model module.
 * @module model/LimitsAttachments
 * @version 0.0.1
 */
class LimitsAttachments {
    /**
     * Constructs a new <code>LimitsAttachments</code>.
     * @alias module:model/LimitsAttachments
     */
    constructor() { 
        
        LimitsAttachments.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LimitsAttachments</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LimitsAttachments} obj Optional instance to populate.
     * @return {module:model/LimitsAttachments} The populated <code>LimitsAttachments</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LimitsAttachments();

            if (data.hasOwnProperty('perBoard')) {
                obj['perBoard'] = LimitsObject.constructFromObject(data['perBoard']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/LimitsObject} perBoard
 */
LimitsAttachments.prototype['perBoard'] = undefined;






export default LimitsAttachments;

