/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LimitsObject model module.
 * @module model/LimitsObject
 * @version 0.0.1
 */
class LimitsObject {
    /**
     * Constructs a new <code>LimitsObject</code>.
     * @alias module:model/LimitsObject
     */
    constructor() { 
        
        LimitsObject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LimitsObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LimitsObject} obj Optional instance to populate.
     * @return {module:model/LimitsObject} The populated <code>LimitsObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LimitsObject();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('disableAt')) {
                obj['disableAt'] = ApiClient.convertToType(data['disableAt'], 'Number');
            }
            if (data.hasOwnProperty('warnAt')) {
                obj['warnAt'] = ApiClient.convertToType(data['warnAt'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/LimitsObject.StatusEnum} status
 */
LimitsObject.prototype['status'] = undefined;

/**
 * @member {Number} disableAt
 */
LimitsObject.prototype['disableAt'] = undefined;

/**
 * @member {Number} warnAt
 */
LimitsObject.prototype['warnAt'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
LimitsObject['StatusEnum'] = {

    /**
     * value: "ok"
     * @const
     */
    "ok": "ok",

    /**
     * value: "warning"
     * @const
     */
    "warning": "warning"
};



export default LimitsObject;

