/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MemberPrefsTwoFactor model module.
 * @module model/MemberPrefsTwoFactor
 * @version 0.0.1
 */
class MemberPrefsTwoFactor {
    /**
     * Constructs a new <code>MemberPrefsTwoFactor</code>.
     * @alias module:model/MemberPrefsTwoFactor
     */
    constructor() { 
        
        MemberPrefsTwoFactor.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MemberPrefsTwoFactor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MemberPrefsTwoFactor} obj Optional instance to populate.
     * @return {module:model/MemberPrefsTwoFactor} The populated <code>MemberPrefsTwoFactor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MemberPrefsTwoFactor();

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('needsNewBackups')) {
                obj['needsNewBackups'] = ApiClient.convertToType(data['needsNewBackups'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} enabled
 */
MemberPrefsTwoFactor.prototype['enabled'] = undefined;

/**
 * @member {Boolean} needsNewBackups
 */
MemberPrefsTwoFactor.prototype['needsNewBackups'] = undefined;






export default MemberPrefsTwoFactor;

