/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CardDescData from './CardDescData';
import LimitsObject from './LimitsObject';
import MemberMarketingOptIn from './MemberMarketingOptIn';
import MemberMessagesDismissed from './MemberMessagesDismissed';
import MemberPrefs from './MemberPrefs';

/**
 * The Member model module.
 * @module model/Member
 * @version 0.0.1
 */
class Member {
    /**
     * Constructs a new <code>Member</code>.
     * @alias module:model/Member
     */
    constructor() { 
        
        Member.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Member</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Member} obj Optional instance to populate.
     * @return {module:model/Member} The populated <code>Member</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Member();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('activityBlocked')) {
                obj['activityBlocked'] = ApiClient.convertToType(data['activityBlocked'], 'Boolean');
            }
            if (data.hasOwnProperty('avatarHash')) {
                obj['avatarHash'] = ApiClient.convertToType(data['avatarHash'], 'String');
            }
            if (data.hasOwnProperty('avatarUrl')) {
                obj['avatarUrl'] = ApiClient.convertToType(data['avatarUrl'], 'String');
            }
            if (data.hasOwnProperty('bio')) {
                obj['bio'] = ApiClient.convertToType(data['bio'], 'String');
            }
            if (data.hasOwnProperty('bioData')) {
                obj['bioData'] = CardDescData.constructFromObject(data['bioData']);
            }
            if (data.hasOwnProperty('confirmed')) {
                obj['confirmed'] = ApiClient.convertToType(data['confirmed'], 'Boolean');
            }
            if (data.hasOwnProperty('fullName')) {
                obj['fullName'] = ApiClient.convertToType(data['fullName'], 'String');
            }
            if (data.hasOwnProperty('idEnterprise')) {
                obj['idEnterprise'] = ApiClient.convertToType(data['idEnterprise'], 'String');
            }
            if (data.hasOwnProperty('idEnterprisesDeactivated')) {
                obj['idEnterprisesDeactivated'] = ApiClient.convertToType(data['idEnterprisesDeactivated'], ['String']);
            }
            if (data.hasOwnProperty('idMemberReferrer')) {
                obj['idMemberReferrer'] = ApiClient.convertToType(data['idMemberReferrer'], 'String');
            }
            if (data.hasOwnProperty('idPremOrgsAdmin')) {
                obj['idPremOrgsAdmin'] = ApiClient.convertToType(data['idPremOrgsAdmin'], ['String']);
            }
            if (data.hasOwnProperty('initials')) {
                obj['initials'] = ApiClient.convertToType(data['initials'], 'String');
            }
            if (data.hasOwnProperty('memberType')) {
                obj['memberType'] = ApiClient.convertToType(data['memberType'], 'String');
            }
            if (data.hasOwnProperty('nonPublic')) {
                obj['nonPublic'] = ApiClient.convertToType(data['nonPublic'], Object);
            }
            if (data.hasOwnProperty('nonPublicAvailable')) {
                obj['nonPublicAvailable'] = ApiClient.convertToType(data['nonPublicAvailable'], 'Boolean');
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], ['Number']);
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('aaEmail')) {
                obj['aaEmail'] = ApiClient.convertToType(data['aaEmail'], 'String');
            }
            if (data.hasOwnProperty('aaEnrolledDate')) {
                obj['aaEnrolledDate'] = ApiClient.convertToType(data['aaEnrolledDate'], 'String');
            }
            if (data.hasOwnProperty('aaId')) {
                obj['aaId'] = ApiClient.convertToType(data['aaId'], 'String');
            }
            if (data.hasOwnProperty('avatarSource')) {
                obj['avatarSource'] = ApiClient.convertToType(data['avatarSource'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('gravatarHash')) {
                obj['gravatarHash'] = ApiClient.convertToType(data['gravatarHash'], 'String');
            }
            if (data.hasOwnProperty('idBoards')) {
                obj['idBoards'] = ApiClient.convertToType(data['idBoards'], ['String']);
            }
            if (data.hasOwnProperty('idOrganizations')) {
                obj['idOrganizations'] = ApiClient.convertToType(data['idOrganizations'], ['String']);
            }
            if (data.hasOwnProperty('idEnterprisesAdmin')) {
                obj['idEnterprisesAdmin'] = ApiClient.convertToType(data['idEnterprisesAdmin'], ['String']);
            }
            if (data.hasOwnProperty('limits')) {
                obj['limits'] = LimitsObject.constructFromObject(data['limits']);
            }
            if (data.hasOwnProperty('loginTypes')) {
                obj['loginTypes'] = ApiClient.convertToType(data['loginTypes'], ['String']);
            }
            if (data.hasOwnProperty('marketingOptIn')) {
                obj['marketingOptIn'] = MemberMarketingOptIn.constructFromObject(data['marketingOptIn']);
            }
            if (data.hasOwnProperty('messagesDismissed')) {
                obj['messagesDismissed'] = MemberMessagesDismissed.constructFromObject(data['messagesDismissed']);
            }
            if (data.hasOwnProperty('oneTimeMessagesDismissed')) {
                obj['oneTimeMessagesDismissed'] = ApiClient.convertToType(data['oneTimeMessagesDismissed'], ['String']);
            }
            if (data.hasOwnProperty('prefs')) {
                obj['prefs'] = MemberPrefs.constructFromObject(data['prefs']);
            }
            if (data.hasOwnProperty('trophies')) {
                obj['trophies'] = ApiClient.convertToType(data['trophies'], ['String']);
            }
            if (data.hasOwnProperty('uploadedAvatarHash')) {
                obj['uploadedAvatarHash'] = ApiClient.convertToType(data['uploadedAvatarHash'], 'String');
            }
            if (data.hasOwnProperty('uploadedAvatarUrl')) {
                obj['uploadedAvatarUrl'] = ApiClient.convertToType(data['uploadedAvatarUrl'], 'String');
            }
            if (data.hasOwnProperty('premiumFeatures')) {
                obj['premiumFeatures'] = ApiClient.convertToType(data['premiumFeatures'], ['String']);
            }
            if (data.hasOwnProperty('isAaMastered')) {
                obj['isAaMastered'] = ApiClient.convertToType(data['isAaMastered'], 'Boolean');
            }
            if (data.hasOwnProperty('ixUpdate')) {
                obj['ixUpdate'] = ApiClient.convertToType(data['ixUpdate'], 'Number');
            }
            if (data.hasOwnProperty('idBoardsPinned')) {
                obj['idBoardsPinned'] = ApiClient.convertToType(data['idBoardsPinned'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Member.prototype['id'] = undefined;

/**
 * @member {Boolean} activityBlocked
 */
Member.prototype['activityBlocked'] = undefined;

/**
 * @member {String} avatarHash
 */
Member.prototype['avatarHash'] = undefined;

/**
 * @member {String} avatarUrl
 */
Member.prototype['avatarUrl'] = undefined;

/**
 * @member {String} bio
 */
Member.prototype['bio'] = undefined;

/**
 * @member {module:model/CardDescData} bioData
 */
Member.prototype['bioData'] = undefined;

/**
 * @member {Boolean} confirmed
 */
Member.prototype['confirmed'] = undefined;

/**
 * @member {String} fullName
 */
Member.prototype['fullName'] = undefined;

/**
 * @member {String} idEnterprise
 */
Member.prototype['idEnterprise'] = undefined;

/**
 * @member {Array.<String>} idEnterprisesDeactivated
 */
Member.prototype['idEnterprisesDeactivated'] = undefined;

/**
 * @member {String} idMemberReferrer
 */
Member.prototype['idMemberReferrer'] = undefined;

/**
 * @member {Array.<String>} idPremOrgsAdmin
 */
Member.prototype['idPremOrgsAdmin'] = undefined;

/**
 * @member {String} initials
 */
Member.prototype['initials'] = undefined;

/**
 * @member {module:model/Member.MemberTypeEnum} memberType
 */
Member.prototype['memberType'] = undefined;

/**
 * @member {Object} nonPublic
 */
Member.prototype['nonPublic'] = undefined;

/**
 * @member {Boolean} nonPublicAvailable
 */
Member.prototype['nonPublicAvailable'] = undefined;

/**
 * @member {Array.<Number>} products
 */
Member.prototype['products'] = undefined;

/**
 * @member {String} url
 */
Member.prototype['url'] = undefined;

/**
 * @member {String} username
 */
Member.prototype['username'] = undefined;

/**
 * @member {module:model/Member.StatusEnum} status
 */
Member.prototype['status'] = undefined;

/**
 * @member {String} aaEmail
 */
Member.prototype['aaEmail'] = undefined;

/**
 * @member {String} aaEnrolledDate
 */
Member.prototype['aaEnrolledDate'] = undefined;

/**
 * @member {String} aaId
 */
Member.prototype['aaId'] = undefined;

/**
 * @member {module:model/Member.AvatarSourceEnum} avatarSource
 */
Member.prototype['avatarSource'] = undefined;

/**
 * @member {String} email
 */
Member.prototype['email'] = undefined;

/**
 * @member {String} gravatarHash
 */
Member.prototype['gravatarHash'] = undefined;

/**
 * @member {Array.<String>} idBoards
 */
Member.prototype['idBoards'] = undefined;

/**
 * @member {Array.<String>} idOrganizations
 */
Member.prototype['idOrganizations'] = undefined;

/**
 * @member {Array.<String>} idEnterprisesAdmin
 */
Member.prototype['idEnterprisesAdmin'] = undefined;

/**
 * @member {module:model/LimitsObject} limits
 */
Member.prototype['limits'] = undefined;

/**
 * @member {Array.<module:model/Member.LoginTypesEnum>} loginTypes
 */
Member.prototype['loginTypes'] = undefined;

/**
 * @member {module:model/MemberMarketingOptIn} marketingOptIn
 */
Member.prototype['marketingOptIn'] = undefined;

/**
 * @member {module:model/MemberMessagesDismissed} messagesDismissed
 */
Member.prototype['messagesDismissed'] = undefined;

/**
 * @member {Array.<String>} oneTimeMessagesDismissed
 */
Member.prototype['oneTimeMessagesDismissed'] = undefined;

/**
 * @member {module:model/MemberPrefs} prefs
 */
Member.prototype['prefs'] = undefined;

/**
 * @member {Array.<String>} trophies
 */
Member.prototype['trophies'] = undefined;

/**
 * @member {String} uploadedAvatarHash
 */
Member.prototype['uploadedAvatarHash'] = undefined;

/**
 * @member {String} uploadedAvatarUrl
 */
Member.prototype['uploadedAvatarUrl'] = undefined;

/**
 * @member {Array.<String>} premiumFeatures
 */
Member.prototype['premiumFeatures'] = undefined;

/**
 * @member {Boolean} isAaMastered
 */
Member.prototype['isAaMastered'] = undefined;

/**
 * @member {Number} ixUpdate
 */
Member.prototype['ixUpdate'] = undefined;

/**
 * @member {Array.<String>} idBoardsPinned
 */
Member.prototype['idBoardsPinned'] = undefined;





/**
 * Allowed values for the <code>memberType</code> property.
 * @enum {String}
 * @readonly
 */
Member['MemberTypeEnum'] = {

    /**
     * value: "normal"
     * @const
     */
    "normal": "normal",

    /**
     * value: "ghost"
     * @const
     */
    "ghost": "ghost"
};


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
Member['StatusEnum'] = {

    /**
     * value: "disconnected"
     * @const
     */
    "disconnected": "disconnected"
};


/**
 * Allowed values for the <code>avatarSource</code> property.
 * @enum {String}
 * @readonly
 */
Member['AvatarSourceEnum'] = {

    /**
     * value: "gravatar"
     * @const
     */
    "gravatar": "gravatar",

    /**
     * value: "upload"
     * @const
     */
    "upload": "upload"
};


/**
 * Allowed values for the <code>loginTypes</code> property.
 * @enum {String}
 * @readonly
 */
Member['LoginTypesEnum'] = {

    /**
     * value: "password"
     * @const
     */
    "password": "password",

    /**
     * value: "saml"
     * @const
     */
    "saml": "saml"
};



export default Member;

