/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MemberMessagesDismissed model module.
 * @module model/MemberMessagesDismissed
 * @version 0.0.1
 */
class MemberMessagesDismissed {
    /**
     * Constructs a new <code>MemberMessagesDismissed</code>.
     * @alias module:model/MemberMessagesDismissed
     */
    constructor() { 
        
        MemberMessagesDismissed.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MemberMessagesDismissed</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MemberMessagesDismissed} obj Optional instance to populate.
     * @return {module:model/MemberMessagesDismissed} The populated <code>MemberMessagesDismissed</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MemberMessagesDismissed();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'String');
            }
            if (data.hasOwnProperty('lastDismissed')) {
                obj['lastDismissed'] = ApiClient.convertToType(data['lastDismissed'], 'Date');
            }
            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
MemberMessagesDismissed.prototype['name'] = undefined;

/**
 * @member {String} count
 */
MemberMessagesDismissed.prototype['count'] = undefined;

/**
 * @member {Date} lastDismissed
 */
MemberMessagesDismissed.prototype['lastDismissed'] = undefined;

/**
 * @member {String} _id
 */
MemberMessagesDismissed.prototype['_id'] = undefined;






export default MemberMessagesDismissed;

