/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MemberPrefsTimezoneInfo model module.
 * @module model/MemberPrefsTimezoneInfo
 * @version 0.0.1
 */
class MemberPrefsTimezoneInfo {
    /**
     * Constructs a new <code>MemberPrefsTimezoneInfo</code>.
     * @alias module:model/MemberPrefsTimezoneInfo
     */
    constructor() { 
        
        MemberPrefsTimezoneInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MemberPrefsTimezoneInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MemberPrefsTimezoneInfo} obj Optional instance to populate.
     * @return {module:model/MemberPrefsTimezoneInfo} The populated <code>MemberPrefsTimezoneInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MemberPrefsTimezoneInfo();

            if (data.hasOwnProperty('offsetCurrent')) {
                obj['offsetCurrent'] = ApiClient.convertToType(data['offsetCurrent'], 'Number');
            }
            if (data.hasOwnProperty('timezoneCurrent')) {
                obj['timezoneCurrent'] = ApiClient.convertToType(data['timezoneCurrent'], 'String');
            }
            if (data.hasOwnProperty('offsetNext')) {
                obj['offsetNext'] = ApiClient.convertToType(data['offsetNext'], 'Number');
            }
            if (data.hasOwnProperty('dateNext')) {
                obj['dateNext'] = ApiClient.convertToType(data['dateNext'], 'Date');
            }
            if (data.hasOwnProperty('timezoneNext')) {
                obj['timezoneNext'] = ApiClient.convertToType(data['timezoneNext'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} offsetCurrent
 */
MemberPrefsTimezoneInfo.prototype['offsetCurrent'] = undefined;

/**
 * @member {String} timezoneCurrent
 */
MemberPrefsTimezoneInfo.prototype['timezoneCurrent'] = undefined;

/**
 * @member {Number} offsetNext
 */
MemberPrefsTimezoneInfo.prototype['offsetNext'] = undefined;

/**
 * @member {Date} dateNext
 */
MemberPrefsTimezoneInfo.prototype['dateNext'] = undefined;

/**
 * @member {String} timezoneNext
 */
MemberPrefsTimezoneInfo.prototype['timezoneNext'] = undefined;






export default MemberPrefsTimezoneInfo;

