/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExportStatus from './ExportStatus';

/**
 * The ModelExport model module.
 * @module model/ModelExport
 * @version 0.0.1
 */
class ModelExport {
    /**
     * Constructs a new <code>ModelExport</code>.
     * @alias module:model/ModelExport
     */
    constructor() { 
        
        ModelExport.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelExport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelExport} obj Optional instance to populate.
     * @return {module:model/ModelExport} The populated <code>ModelExport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelExport();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ExportStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('startedAt')) {
                obj['startedAt'] = ApiClient.convertToType(data['startedAt'], 'Date');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'String');
            }
            if (data.hasOwnProperty('exportUrl')) {
                obj['exportUrl'] = ApiClient.convertToType(data['exportUrl'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ModelExport.prototype['id'] = undefined;

/**
 * @member {module:model/ExportStatus} status
 */
ModelExport.prototype['status'] = undefined;

/**
 * @member {Date} startedAt
 */
ModelExport.prototype['startedAt'] = undefined;

/**
 * @member {String} size
 */
ModelExport.prototype['size'] = undefined;

/**
 * @member {String} exportUrl
 */
ModelExport.prototype['exportUrl'] = undefined;






export default ModelExport;

