/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class NotificationFields.
* @enum {}
* @readonly
*/
export default class NotificationFields {
    
        /**
         * value: "id"
         * @const
         */
        "id" = "id";

    
        /**
         * value: "unread"
         * @const
         */
        "unread" = "unread";

    
        /**
         * value: "type"
         * @const
         */
        "type" = "type";

    
        /**
         * value: "date"
         * @const
         */
        "date" = "date";

    
        /**
         * value: "dateRead"
         * @const
         */
        "dateRead" = "dateRead";

    
        /**
         * value: "data"
         * @const
         */
        "data" = "data";

    
        /**
         * value: "card"
         * @const
         */
        "card" = "card";

    
        /**
         * value: "board"
         * @const
         */
        "board" = "board";

    
        /**
         * value: "idMemberCreator"
         * @const
         */
        "idMemberCreator" = "idMemberCreator";

    
        /**
         * value: "idAction"
         * @const
         */
        "idAction" = "idAction";

    
        /**
         * value: "reactions"
         * @const
         */
        "reactions" = "reactions";

    

    /**
    * Returns a <code>NotificationFields</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/NotificationFields} The enum <code>NotificationFields</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

