/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PluginListing model module.
 * @module model/PluginListing
 * @version 0.0.1
 */
class PluginListing {
    /**
     * Constructs a new <code>PluginListing</code>.
     * @alias module:model/PluginListing
     */
    constructor() { 
        
        PluginListing.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PluginListing</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PluginListing} obj Optional instance to populate.
     * @return {module:model/PluginListing} The populated <code>PluginListing</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PluginListing();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('locale')) {
                obj['locale'] = ApiClient.convertToType(data['locale'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('overview')) {
                obj['overview'] = ApiClient.convertToType(data['overview'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
PluginListing.prototype['id'] = undefined;

/**
 * @member {String} name
 */
PluginListing.prototype['name'] = undefined;

/**
 * @member {String} locale
 */
PluginListing.prototype['locale'] = undefined;

/**
 * @member {String} description
 */
PluginListing.prototype['description'] = undefined;

/**
 * @member {String} overview
 */
PluginListing.prototype['overview'] = undefined;






export default PluginListing;

