/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Prefs model module.
 * @module model/Prefs
 * @version 0.0.1
 */
class Prefs {
    /**
     * Constructs a new <code>Prefs</code>.
     * @alias module:model/Prefs
     */
    constructor() { 
        
        Prefs.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Prefs</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Prefs} obj Optional instance to populate.
     * @return {module:model/Prefs} The populated <code>Prefs</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Prefs();

            if (data.hasOwnProperty('permissionLevel')) {
                obj['permissionLevel'] = ApiClient.convertToType(data['permissionLevel'], 'String');
            }
            if (data.hasOwnProperty('hideVotes')) {
                obj['hideVotes'] = ApiClient.convertToType(data['hideVotes'], 'Boolean');
            }
            if (data.hasOwnProperty('voting')) {
                obj['voting'] = ApiClient.convertToType(data['voting'], 'String');
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
            }
            if (data.hasOwnProperty('invitations')) {
                obj['invitations'] = ApiClient.convertToType(data['invitations'], 'String');
            }
            if (data.hasOwnProperty('selfJoin')) {
                obj['selfJoin'] = ApiClient.convertToType(data['selfJoin'], 'Boolean');
            }
            if (data.hasOwnProperty('cardCovers')) {
                obj['cardCovers'] = ApiClient.convertToType(data['cardCovers'], 'Boolean');
            }
            if (data.hasOwnProperty('isTemplate')) {
                obj['isTemplate'] = ApiClient.convertToType(data['isTemplate'], 'Boolean');
            }
            if (data.hasOwnProperty('cardAging')) {
                obj['cardAging'] = ApiClient.convertToType(data['cardAging'], 'String');
            }
            if (data.hasOwnProperty('calendarFeedEnabled')) {
                obj['calendarFeedEnabled'] = ApiClient.convertToType(data['calendarFeedEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('background')) {
                obj['background'] = ApiClient.convertToType(data['background'], 'String');
            }
            if (data.hasOwnProperty('backgroundImage')) {
                obj['backgroundImage'] = ApiClient.convertToType(data['backgroundImage'], 'String');
            }
            if (data.hasOwnProperty('backgroundImageScaled')) {
                obj['backgroundImageScaled'] = ApiClient.convertToType(data['backgroundImageScaled'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Prefs.PermissionLevelEnum} permissionLevel
 */
Prefs.prototype['permissionLevel'] = undefined;

/**
 * @member {Boolean} hideVotes
 */
Prefs.prototype['hideVotes'] = undefined;

/**
 * @member {module:model/Prefs.VotingEnum} voting
 */
Prefs.prototype['voting'] = undefined;

/**
 * @member {String} comments
 */
Prefs.prototype['comments'] = undefined;

/**
 * @member {module:model/Prefs.InvitationsEnum} invitations
 */
Prefs.prototype['invitations'] = undefined;

/**
 * @member {Boolean} selfJoin
 */
Prefs.prototype['selfJoin'] = undefined;

/**
 * @member {Boolean} cardCovers
 */
Prefs.prototype['cardCovers'] = undefined;

/**
 * @member {Boolean} isTemplate
 */
Prefs.prototype['isTemplate'] = undefined;

/**
 * @member {module:model/Prefs.CardAgingEnum} cardAging
 */
Prefs.prototype['cardAging'] = undefined;

/**
 * @member {Boolean} calendarFeedEnabled
 */
Prefs.prototype['calendarFeedEnabled'] = undefined;

/**
 * @member {String} background
 */
Prefs.prototype['background'] = undefined;

/**
 * @member {String} backgroundImage
 */
Prefs.prototype['backgroundImage'] = undefined;

/**
 * @member {String} backgroundImageScaled
 */
Prefs.prototype['backgroundImageScaled'] = undefined;





/**
 * Allowed values for the <code>permissionLevel</code> property.
 * @enum {String}
 * @readonly
 */
Prefs['PermissionLevelEnum'] = {

    /**
     * value: "org"
     * @const
     */
    "org": "org",

    /**
     * value: "board"
     * @const
     */
    "board": "board"
};


/**
 * Allowed values for the <code>voting</code> property.
 * @enum {String}
 * @readonly
 */
Prefs['VotingEnum'] = {

    /**
     * value: "disabled"
     * @const
     */
    "disabled": "disabled",

    /**
     * value: "enabled"
     * @const
     */
    "enabled": "enabled"
};


/**
 * Allowed values for the <code>invitations</code> property.
 * @enum {String}
 * @readonly
 */
Prefs['InvitationsEnum'] = {

    /**
     * value: "admins"
     * @const
     */
    "admins": "admins",

    /**
     * value: "members"
     * @const
     */
    "members": "members"
};


/**
 * Allowed values for the <code>cardAging</code> property.
 * @enum {String}
 * @readonly
 */
Prefs['CardAgingEnum'] = {

    /**
     * value: "pirate"
     * @const
     */
    "pirate": "pirate",

    /**
     * value: "normal"
     * @const
     */
    "normal": "normal"
};



export default Prefs;

