/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PosStringOrNumber from './PosStringOrNumber';

/**
 * The SavedSearch model module.
 * @module model/SavedSearch
 * @version 0.0.1
 */
class SavedSearch {
    /**
     * Constructs a new <code>SavedSearch</code>.
     * @alias module:model/SavedSearch
     */
    constructor() { 
        
        SavedSearch.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SavedSearch</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SavedSearch} obj Optional instance to populate.
     * @return {module:model/SavedSearch} The populated <code>SavedSearch</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SavedSearch();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('query')) {
                obj['query'] = ApiClient.convertToType(data['query'], 'String');
            }
            if (data.hasOwnProperty('pos')) {
                obj['pos'] = PosStringOrNumber.constructFromObject(data['pos']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
SavedSearch.prototype['id'] = undefined;

/**
 * @member {String} name
 */
SavedSearch.prototype['name'] = undefined;

/**
 * @member {String} query
 */
SavedSearch.prototype['query'] = undefined;

/**
 * @member {module:model/PosStringOrNumber} pos
 */
SavedSearch.prototype['pos'] = undefined;






export default SavedSearch;

