/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OneOfstringstring from './OneOfstringstring';

/**
 * The TokenPermission model module.
 * @module model/TokenPermission
 * @version 0.0.1
 */
class TokenPermission {
    /**
     * Constructs a new <code>TokenPermission</code>.
     * @alias module:model/TokenPermission
     */
    constructor() { 
        
        TokenPermission.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TokenPermission</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TokenPermission} obj Optional instance to populate.
     * @return {module:model/TokenPermission} The populated <code>TokenPermission</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TokenPermission();

            if (data.hasOwnProperty('idModel')) {
                obj['idModel'] = ApiClient.convertToType(data['idModel'], OneOfstringstring);
            }
            if (data.hasOwnProperty('modelType')) {
                obj['modelType'] = ApiClient.convertToType(data['modelType'], 'String');
            }
            if (data.hasOwnProperty('read')) {
                obj['read'] = ApiClient.convertToType(data['read'], 'Boolean');
            }
            if (data.hasOwnProperty('write')) {
                obj['write'] = ApiClient.convertToType(data['write'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/OneOfstringstring} idModel
 */
TokenPermission.prototype['idModel'] = undefined;

/**
 * @member {module:model/TokenPermission.ModelTypeEnum} modelType
 */
TokenPermission.prototype['modelType'] = undefined;

/**
 * @member {Boolean} read
 */
TokenPermission.prototype['read'] = undefined;

/**
 * @member {Boolean} write
 */
TokenPermission.prototype['write'] = undefined;





/**
 * Allowed values for the <code>modelType</code> property.
 * @enum {String}
 * @readonly
 */
TokenPermission['ModelTypeEnum'] = {

    /**
     * value: "board"
     * @const
     */
    "board": "board",

    /**
     * value: "member"
     * @const
     */
    "member": "member",

    /**
     * value: "organization"
     * @const
     */
    "organization": "organization",

    /**
     * value: "enterprise"
     * @const
     */
    "enterprise": "enterprise"
};



export default TokenPermission;

