/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TokenFields.
* @enum {}
* @readonly
*/
export default class TokenFields {
    
        /**
         * value: "identifier"
         * @const
         */
        "identifier" = "identifier";

    
        /**
         * value: "idMember"
         * @const
         */
        "idMember" = "idMember";

    
        /**
         * value: "dateCreated"
         * @const
         */
        "dateCreated" = "dateCreated";

    
        /**
         * value: "dateExpires"
         * @const
         */
        "dateExpires" = "dateExpires";

    
        /**
         * value: "permissions"
         * @const
         */
        "permissions" = "permissions";

    

    /**
    * Returns a <code>TokenFields</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/TokenFields} The enum <code>TokenFields</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

