/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TokenPermission from './TokenPermission';

/**
 * The Token model module.
 * @module model/Token
 * @version 0.0.1
 */
class Token {
    /**
     * Constructs a new <code>Token</code>.
     * @alias module:model/Token
     */
    constructor() { 
        
        Token.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Token</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Token} obj Optional instance to populate.
     * @return {module:model/Token} The populated <code>Token</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Token();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('idMember')) {
                obj['idMember'] = ApiClient.convertToType(data['idMember'], 'String');
            }
            if (data.hasOwnProperty('dateCreated')) {
                obj['dateCreated'] = ApiClient.convertToType(data['dateCreated'], 'Date');
            }
            if (data.hasOwnProperty('dateExpires')) {
                obj['dateExpires'] = ApiClient.convertToType(data['dateExpires'], 'Date');
            }
            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], [TokenPermission]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Token.prototype['id'] = undefined;

/**
 * @member {String} identifier
 */
Token.prototype['identifier'] = undefined;

/**
 * @member {String} idMember
 */
Token.prototype['idMember'] = undefined;

/**
 * @member {Date} dateCreated
 */
Token.prototype['dateCreated'] = undefined;

/**
 * @member {Date} dateExpires
 */
Token.prototype['dateExpires'] = undefined;

/**
 * @member {Array.<module:model/TokenPermission>} permissions
 */
Token.prototype['permissions'] = undefined;






export default Token;

