/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ViewFilter.
* @enum {}
* @readonly
*/
export default class ViewFilter {
    
        /**
         * value: "all"
         * @const
         */
        "all" = "all";

    
        /**
         * value: "closed"
         * @const
         */
        "closed" = "closed";

    
        /**
         * value: "none"
         * @const
         */
        "none" = "none";

    
        /**
         * value: "open"
         * @const
         */
        "open" = "open";

    

    /**
    * Returns a <code>ViewFilter</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ViewFilter} The enum <code>ViewFilter</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

