/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Webhook model module.
 * @module model/Webhook
 * @version 0.0.1
 */
class Webhook {
    /**
     * Constructs a new <code>Webhook</code>.
     * @alias module:model/Webhook
     */
    constructor() { 
        
        Webhook.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Webhook</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Webhook} obj Optional instance to populate.
     * @return {module:model/Webhook} The populated <code>Webhook</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Webhook();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('idModel')) {
                obj['idModel'] = ApiClient.convertToType(data['idModel'], 'String');
            }
            if (data.hasOwnProperty('callbackURL')) {
                obj['callbackURL'] = ApiClient.convertToType(data['callbackURL'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('consecutiveFailures')) {
                obj['consecutiveFailures'] = ApiClient.convertToType(data['consecutiveFailures'], 'Number');
            }
            if (data.hasOwnProperty('firstConsecutiveFailDate')) {
                obj['firstConsecutiveFailDate'] = ApiClient.convertToType(data['firstConsecutiveFailDate'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Webhook.prototype['id'] = undefined;

/**
 * @member {String} description
 */
Webhook.prototype['description'] = undefined;

/**
 * @member {String} idModel
 */
Webhook.prototype['idModel'] = undefined;

/**
 * @member {String} callbackURL
 */
Webhook.prototype['callbackURL'] = undefined;

/**
 * @member {Boolean} active
 */
Webhook.prototype['active'] = undefined;

/**
 * @member {Number} consecutiveFailures
 */
Webhook.prototype['consecutiveFailures'] = undefined;

/**
 * @member {Date} firstConsecutiveFailDate
 */
Webhook.prototype['firstConsecutiveFailDate'] = undefined;






export default Webhook;

