/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrelloRestApi);
  }
}(this, function(expect, TrelloRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrelloRestApi.BoardLabelNames();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BoardLabelNames', function() {
    it('should create an instance of BoardLabelNames', function() {
      // uncomment below and update the code to test BoardLabelNames
      //var instane = new TrelloRestApi.BoardLabelNames();
      //expect(instance).to.be.a(TrelloRestApi.BoardLabelNames);
    });

    it('should have the property green (base name: "green")', function() {
      // uncomment below and update the code to test the property green
      //var instane = new TrelloRestApi.BoardLabelNames();
      //expect(instance).to.be();
    });

    it('should have the property yellow (base name: "yellow")', function() {
      // uncomment below and update the code to test the property yellow
      //var instane = new TrelloRestApi.BoardLabelNames();
      //expect(instance).to.be();
    });

    it('should have the property orange (base name: "orange")', function() {
      // uncomment below and update the code to test the property orange
      //var instane = new TrelloRestApi.BoardLabelNames();
      //expect(instance).to.be();
    });

    it('should have the property red (base name: "red")', function() {
      // uncomment below and update the code to test the property red
      //var instane = new TrelloRestApi.BoardLabelNames();
      //expect(instance).to.be();
    });

    it('should have the property purple (base name: "purple")', function() {
      // uncomment below and update the code to test the property purple
      //var instane = new TrelloRestApi.BoardLabelNames();
      //expect(instance).to.be();
    });

    it('should have the property blue (base name: "blue")', function() {
      // uncomment below and update the code to test the property blue
      //var instane = new TrelloRestApi.BoardLabelNames();
      //expect(instance).to.be();
    });

    it('should have the property sky (base name: "sky")', function() {
      // uncomment below and update the code to test the property sky
      //var instane = new TrelloRestApi.BoardLabelNames();
      //expect(instance).to.be();
    });

    it('should have the property lime (base name: "lime")', function() {
      // uncomment below and update the code to test the property lime
      //var instane = new TrelloRestApi.BoardLabelNames();
      //expect(instance).to.be();
    });

    it('should have the property pink (base name: "pink")', function() {
      // uncomment below and update the code to test the property pink
      //var instane = new TrelloRestApi.BoardLabelNames();
      //expect(instance).to.be();
    });

    it('should have the property black (base name: "black")', function() {
      // uncomment below and update the code to test the property black
      //var instane = new TrelloRestApi.BoardLabelNames();
      //expect(instance).to.be();
    });

  });

}));
