/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrelloRestApi);
  }
}(this, function(expect, TrelloRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrelloRestApi.CustomFieldDisplay();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CustomFieldDisplay', function() {
    it('should create an instance of CustomFieldDisplay', function() {
      // uncomment below and update the code to test CustomFieldDisplay
      //var instane = new TrelloRestApi.CustomFieldDisplay();
      //expect(instance).to.be.a(TrelloRestApi.CustomFieldDisplay);
    });

    it('should have the property cardFront (base name: "cardFront")', function() {
      // uncomment below and update the code to test the property cardFront
      //var instane = new TrelloRestApi.CustomFieldDisplay();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new TrelloRestApi.CustomFieldDisplay();
      //expect(instance).to.be();
    });

    it('should have the property pos (base name: "pos")', function() {
      // uncomment below and update the code to test the property pos
      //var instane = new TrelloRestApi.CustomFieldDisplay();
      //expect(instance).to.be();
    });

    it('should have the property options (base name: "options")', function() {
      // uncomment below and update the code to test the property options
      //var instane = new TrelloRestApi.CustomFieldDisplay();
      //expect(instance).to.be();
    });

  });

}));
