/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrelloRestApi);
  }
}(this, function(expect, TrelloRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrelloRestApi.EnterprisePrefs();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EnterprisePrefs', function() {
    it('should create an instance of EnterprisePrefs', function() {
      // uncomment below and update the code to test EnterprisePrefs
      //var instane = new TrelloRestApi.EnterprisePrefs();
      //expect(instance).to.be.a(TrelloRestApi.EnterprisePrefs);
    });

    it('should have the property ssoOnly (base name: "ssoOnly")', function() {
      // uncomment below and update the code to test the property ssoOnly
      //var instane = new TrelloRestApi.EnterprisePrefs();
      //expect(instance).to.be();
    });

    it('should have the property signup (base name: "signup")', function() {
      // uncomment below and update the code to test the property signup
      //var instane = new TrelloRestApi.EnterprisePrefs();
      //expect(instance).to.be();
    });

    it('should have the property mandatoryTransferDate (base name: "mandatoryTransferDate")', function() {
      // uncomment below and update the code to test the property mandatoryTransferDate
      //var instane = new TrelloRestApi.EnterprisePrefs();
      //expect(instance).to.be();
    });

    it('should have the property brandingColor (base name: "brandingColor")', function() {
      // uncomment below and update the code to test the property brandingColor
      //var instane = new TrelloRestApi.EnterprisePrefs();
      //expect(instance).to.be();
    });

    it('should have the property autoJoinOrganizations (base name: "autoJoinOrganizations")', function() {
      // uncomment below and update the code to test the property autoJoinOrganizations
      //var instane = new TrelloRestApi.EnterprisePrefs();
      //expect(instance).to.be();
    });

    it('should have the property notifications (base name: "notifications")', function() {
      // uncomment below and update the code to test the property notifications
      //var instane = new TrelloRestApi.EnterprisePrefs();
      //expect(instance).to.be();
    });

    it('should have the property maxMembers (base name: "maxMembers")', function() {
      // uncomment below and update the code to test the property maxMembers
      //var instane = new TrelloRestApi.EnterprisePrefs();
      //expect(instance).to.be();
    });

  });

}));
