/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrelloRestApi);
  }
}(this, function(expect, TrelloRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrelloRestApi.InlineObject2();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineObject2', function() {
    it('should create an instance of InlineObject2', function() {
      // uncomment below and update the code to test InlineObject2
      //var instane = new TrelloRestApi.InlineObject2();
      //expect(instance).to.be.a(TrelloRestApi.InlineObject2);
    });

    it('should have the property idModel (base name: "idModel")', function() {
      // uncomment below and update the code to test the property idModel
      //var instane = new TrelloRestApi.InlineObject2();
      //expect(instance).to.be();
    });

    it('should have the property modelType (base name: "modelType")', function() {
      // uncomment below and update the code to test the property modelType
      //var instane = new TrelloRestApi.InlineObject2();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new TrelloRestApi.InlineObject2();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new TrelloRestApi.InlineObject2();
      //expect(instance).to.be();
    });

    it('should have the property options (base name: "options")', function() {
      // uncomment below and update the code to test the property options
      //var instane = new TrelloRestApi.InlineObject2();
      //expect(instance).to.be();
    });

    it('should have the property pos (base name: "pos")', function() {
      // uncomment below and update the code to test the property pos
      //var instane = new TrelloRestApi.InlineObject2();
      //expect(instance).to.be();
    });

    it('should have the property displayCardFront (base name: "display_cardFront")', function() {
      // uncomment below and update the code to test the property displayCardFront
      //var instane = new TrelloRestApi.InlineObject2();
      //expect(instance).to.be();
    });

  });

}));
