/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrelloRestApi);
  }
}(this, function(expect, TrelloRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrelloRestApi.InlineObject();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineObject', function() {
    it('should create an instance of InlineObject', function() {
      // uncomment below and update the code to test InlineObject
      //var instane = new TrelloRestApi.InlineObject();
      //expect(instance).to.be.a(TrelloRestApi.InlineObject);
    });

    it('should have the property shortName (base name: "shortName")', function() {
      // uncomment below and update the code to test the property shortName
      //var instane = new TrelloRestApi.InlineObject();
      //expect(instance).to.be();
    });

    it('should have the property skinVariation (base name: "skinVariation")', function() {
      // uncomment below and update the code to test the property skinVariation
      //var instane = new TrelloRestApi.InlineObject();
      //expect(instance).to.be();
    });

    it('should have the property _native (base name: "native")', function() {
      // uncomment below and update the code to test the property _native
      //var instane = new TrelloRestApi.InlineObject();
      //expect(instance).to.be();
    });

    it('should have the property unified (base name: "unified")', function() {
      // uncomment below and update the code to test the property unified
      //var instane = new TrelloRestApi.InlineObject();
      //expect(instance).to.be();
    });

  });

}));
