/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrelloRestApi);
  }
}(this, function(expect, TrelloRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrelloRestApi.MemberPrefs();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MemberPrefs', function() {
    it('should create an instance of MemberPrefs', function() {
      // uncomment below and update the code to test MemberPrefs
      //var instane = new TrelloRestApi.MemberPrefs();
      //expect(instance).to.be.a(TrelloRestApi.MemberPrefs);
    });

    it('should have the property timezoneInfo (base name: "timezoneInfo")', function() {
      // uncomment below and update the code to test the property timezoneInfo
      //var instane = new TrelloRestApi.MemberPrefs();
      //expect(instance).to.be();
    });

    it('should have the property privacy (base name: "privacy")', function() {
      // uncomment below and update the code to test the property privacy
      //var instane = new TrelloRestApi.MemberPrefs();
      //expect(instance).to.be();
    });

    it('should have the property sendSummaries (base name: "sendSummaries")', function() {
      // uncomment below and update the code to test the property sendSummaries
      //var instane = new TrelloRestApi.MemberPrefs();
      //expect(instance).to.be();
    });

    it('should have the property minutesBetweenSummaries (base name: "minutesBetweenSummaries")', function() {
      // uncomment below and update the code to test the property minutesBetweenSummaries
      //var instane = new TrelloRestApi.MemberPrefs();
      //expect(instance).to.be();
    });

    it('should have the property minutesBeforeDeadlineToNotify (base name: "minutesBeforeDeadlineToNotify")', function() {
      // uncomment below and update the code to test the property minutesBeforeDeadlineToNotify
      //var instane = new TrelloRestApi.MemberPrefs();
      //expect(instance).to.be();
    });

    it('should have the property colorBlind (base name: "colorBlind")', function() {
      // uncomment below and update the code to test the property colorBlind
      //var instane = new TrelloRestApi.MemberPrefs();
      //expect(instance).to.be();
    });

    it('should have the property locale (base name: "locale")', function() {
      // uncomment below and update the code to test the property locale
      //var instane = new TrelloRestApi.MemberPrefs();
      //expect(instance).to.be();
    });

    it('should have the property timezone (base name: "timezone")', function() {
      // uncomment below and update the code to test the property timezone
      //var instane = new TrelloRestApi.MemberPrefs();
      //expect(instance).to.be();
    });

    it('should have the property twoFactor (base name: "twoFactor")', function() {
      // uncomment below and update the code to test the property twoFactor
      //var instane = new TrelloRestApi.MemberPrefs();
      //expect(instance).to.be();
    });

  });

}));
