/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrelloRestApi);
  }
}(this, function(expect, TrelloRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrelloRestApi.Notification();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Notification', function() {
    it('should create an instance of Notification', function() {
      // uncomment below and update the code to test Notification
      //var instane = new TrelloRestApi.Notification();
      //expect(instance).to.be.a(TrelloRestApi.Notification);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new TrelloRestApi.Notification();
      //expect(instance).to.be();
    });

    it('should have the property unread (base name: "unread")', function() {
      // uncomment below and update the code to test the property unread
      //var instane = new TrelloRestApi.Notification();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new TrelloRestApi.Notification();
      //expect(instance).to.be();
    });

    it('should have the property _date (base name: "date")', function() {
      // uncomment below and update the code to test the property _date
      //var instane = new TrelloRestApi.Notification();
      //expect(instance).to.be();
    });

    it('should have the property dateRead (base name: "dateRead")', function() {
      // uncomment below and update the code to test the property dateRead
      //var instane = new TrelloRestApi.Notification();
      //expect(instance).to.be();
    });

    it('should have the property data (base name: "data")', function() {
      // uncomment below and update the code to test the property data
      //var instane = new TrelloRestApi.Notification();
      //expect(instance).to.be();
    });

    it('should have the property card (base name: "card")', function() {
      // uncomment below and update the code to test the property card
      //var instane = new TrelloRestApi.Notification();
      //expect(instance).to.be();
    });

    it('should have the property board (base name: "board")', function() {
      // uncomment below and update the code to test the property board
      //var instane = new TrelloRestApi.Notification();
      //expect(instance).to.be();
    });

    it('should have the property idMemberCreator (base name: "idMemberCreator")', function() {
      // uncomment below and update the code to test the property idMemberCreator
      //var instane = new TrelloRestApi.Notification();
      //expect(instance).to.be();
    });

    it('should have the property idAction (base name: "idAction")', function() {
      // uncomment below and update the code to test the property idAction
      //var instane = new TrelloRestApi.Notification();
      //expect(instance).to.be();
    });

    it('should have the property reactions (base name: "reactions")', function() {
      // uncomment below and update the code to test the property reactions
      //var instane = new TrelloRestApi.Notification();
      //expect(instance).to.be();
    });

  });

}));
