/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrelloRestApi);
  }
}(this, function(expect, TrelloRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrelloRestApi.Prefs();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Prefs', function() {
    it('should create an instance of Prefs', function() {
      // uncomment below and update the code to test Prefs
      //var instane = new TrelloRestApi.Prefs();
      //expect(instance).to.be.a(TrelloRestApi.Prefs);
    });

    it('should have the property permissionLevel (base name: "permissionLevel")', function() {
      // uncomment below and update the code to test the property permissionLevel
      //var instane = new TrelloRestApi.Prefs();
      //expect(instance).to.be();
    });

    it('should have the property hideVotes (base name: "hideVotes")', function() {
      // uncomment below and update the code to test the property hideVotes
      //var instane = new TrelloRestApi.Prefs();
      //expect(instance).to.be();
    });

    it('should have the property voting (base name: "voting")', function() {
      // uncomment below and update the code to test the property voting
      //var instane = new TrelloRestApi.Prefs();
      //expect(instance).to.be();
    });

    it('should have the property comments (base name: "comments")', function() {
      // uncomment below and update the code to test the property comments
      //var instane = new TrelloRestApi.Prefs();
      //expect(instance).to.be();
    });

    it('should have the property invitations (base name: "invitations")', function() {
      // uncomment below and update the code to test the property invitations
      //var instane = new TrelloRestApi.Prefs();
      //expect(instance).to.be();
    });

    it('should have the property selfJoin (base name: "selfJoin")', function() {
      // uncomment below and update the code to test the property selfJoin
      //var instane = new TrelloRestApi.Prefs();
      //expect(instance).to.be();
    });

    it('should have the property cardCovers (base name: "cardCovers")', function() {
      // uncomment below and update the code to test the property cardCovers
      //var instane = new TrelloRestApi.Prefs();
      //expect(instance).to.be();
    });

    it('should have the property isTemplate (base name: "isTemplate")', function() {
      // uncomment below and update the code to test the property isTemplate
      //var instane = new TrelloRestApi.Prefs();
      //expect(instance).to.be();
    });

    it('should have the property cardAging (base name: "cardAging")', function() {
      // uncomment below and update the code to test the property cardAging
      //var instane = new TrelloRestApi.Prefs();
      //expect(instance).to.be();
    });

    it('should have the property calendarFeedEnabled (base name: "calendarFeedEnabled")', function() {
      // uncomment below and update the code to test the property calendarFeedEnabled
      //var instane = new TrelloRestApi.Prefs();
      //expect(instance).to.be();
    });

    it('should have the property background (base name: "background")', function() {
      // uncomment below and update the code to test the property background
      //var instane = new TrelloRestApi.Prefs();
      //expect(instance).to.be();
    });

    it('should have the property backgroundImage (base name: "backgroundImage")', function() {
      // uncomment below and update the code to test the property backgroundImage
      //var instane = new TrelloRestApi.Prefs();
      //expect(instance).to.be();
    });

    it('should have the property backgroundImageScaled (base name: "backgroundImageScaled")', function() {
      // uncomment below and update the code to test the property backgroundImageScaled
      //var instane = new TrelloRestApi.Prefs();
      //expect(instance).to.be();
    });

  });

}));
