/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrelloRestApi);
  }
}(this, function(expect, TrelloRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrelloRestApi.Webhook();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Webhook', function() {
    it('should create an instance of Webhook', function() {
      // uncomment below and update the code to test Webhook
      //var instane = new TrelloRestApi.Webhook();
      //expect(instance).to.be.a(TrelloRestApi.Webhook);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new TrelloRestApi.Webhook();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new TrelloRestApi.Webhook();
      //expect(instance).to.be();
    });

    it('should have the property idModel (base name: "idModel")', function() {
      // uncomment below and update the code to test the property idModel
      //var instane = new TrelloRestApi.Webhook();
      //expect(instance).to.be();
    });

    it('should have the property callbackURL (base name: "callbackURL")', function() {
      // uncomment below and update the code to test the property callbackURL
      //var instane = new TrelloRestApi.Webhook();
      //expect(instance).to.be();
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instane = new TrelloRestApi.Webhook();
      //expect(instance).to.be();
    });

    it('should have the property consecutiveFailures (base name: "consecutiveFailures")', function() {
      // uncomment below and update the code to test the property consecutiveFailures
      //var instane = new TrelloRestApi.Webhook();
      //expect(instance).to.be();
    });

    it('should have the property firstConsecutiveFailDate (base name: "firstConsecutiveFailDate")', function() {
      // uncomment below and update the code to test the property firstConsecutiveFailDate
      //var instane = new TrelloRestApi.Webhook();
      //expect(instance).to.be();
    });

  });

}));
