/**
 * Trello REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TrelloRestApi);
  }
}(this, function(expect, TrelloRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TrelloRestApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('applicationsKeyCompliance', function() {
      it('should call applicationsKeyCompliance successfully', function(done) {
        //uncomment below and update the code to test applicationsKeyCompliance
        //instance.applicationsKeyCompliance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('boardsIdChecklists', function() {
      it('should call boardsIdChecklists successfully', function(done) {
        //uncomment below and update the code to test boardsIdChecklists
        //instance.boardsIdChecklists(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('boardsidmembersidmember', function() {
      it('should call boardsidmembersidmember successfully', function(done) {
        //uncomment below and update the code to test boardsidmembersidmember
        //instance.boardsidmembersidmember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cardsidmembersvoted1', function() {
      it('should call cardsidmembersvoted1 successfully', function(done) {
        //uncomment below and update the code to test cardsidmembersvoted1
        //instance.cardsidmembersvoted1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteActionsId', function() {
      it('should call deleteActionsId successfully', function(done) {
        //uncomment below and update the code to test deleteActionsId
        //instance.deleteActionsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteActionsIdactionReactionsId', function() {
      it('should call deleteActionsIdactionReactionsId successfully', function(done) {
        //uncomment below and update the code to test deleteActionsIdactionReactionsId
        //instance.deleteActionsIdactionReactionsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteBoardsId', function() {
      it('should call deleteBoardsId successfully', function(done) {
        //uncomment below and update the code to test deleteBoardsId
        //instance.deleteBoardsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteBoardsIdBoardplugins', function() {
      it('should call deleteBoardsIdBoardplugins successfully', function(done) {
        //uncomment below and update the code to test deleteBoardsIdBoardplugins
        //instance.deleteBoardsIdBoardplugins(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteBoardsIdPowerups', function() {
      it('should call deleteBoardsIdPowerups successfully', function(done) {
        //uncomment below and update the code to test deleteBoardsIdPowerups
        //instance.deleteBoardsIdPowerups(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCardsId', function() {
      it('should call deleteCardsId successfully', function(done) {
        //uncomment below and update the code to test deleteCardsId
        //instance.deleteCardsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCardsIdActionsIdComments', function() {
      it('should call deleteCardsIdActionsIdComments successfully', function(done) {
        //uncomment below and update the code to test deleteCardsIdActionsIdComments
        //instance.deleteCardsIdActionsIdComments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCardsIdCheckitemIdcheckitem', function() {
      it('should call deleteCardsIdCheckitemIdcheckitem successfully', function(done) {
        //uncomment below and update the code to test deleteCardsIdCheckitemIdcheckitem
        //instance.deleteCardsIdCheckitemIdcheckitem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCardsIdChecklistsIdchecklist', function() {
      it('should call deleteCardsIdChecklistsIdchecklist successfully', function(done) {
        //uncomment below and update the code to test deleteCardsIdChecklistsIdchecklist
        //instance.deleteCardsIdChecklistsIdchecklist(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCardsIdIdlabelsIdlabel', function() {
      it('should call deleteCardsIdIdlabelsIdlabel successfully', function(done) {
        //uncomment below and update the code to test deleteCardsIdIdlabelsIdlabel
        //instance.deleteCardsIdIdlabelsIdlabel(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCardsIdMembersvotedIdmember', function() {
      it('should call deleteCardsIdMembersvotedIdmember successfully', function(done) {
        //uncomment below and update the code to test deleteCardsIdMembersvotedIdmember
        //instance.deleteCardsIdMembersvotedIdmember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCardsIdStickersIdsticker', function() {
      it('should call deleteCardsIdStickersIdsticker successfully', function(done) {
        //uncomment below and update the code to test deleteCardsIdStickersIdsticker
        //instance.deleteCardsIdStickersIdsticker(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteChecklistsId', function() {
      it('should call deleteChecklistsId successfully', function(done) {
        //uncomment below and update the code to test deleteChecklistsId
        //instance.deleteChecklistsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteChecklistsIdCheckitemsIdcheckitem', function() {
      it('should call deleteChecklistsIdCheckitemsIdcheckitem successfully', function(done) {
        //uncomment below and update the code to test deleteChecklistsIdCheckitemsIdcheckitem
        //instance.deleteChecklistsIdCheckitemsIdcheckitem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCustomfieldsId', function() {
      it('should call deleteCustomfieldsId successfully', function(done) {
        //uncomment below and update the code to test deleteCustomfieldsId
        //instance.deleteCustomfieldsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCustomfieldsOptionsIdcustomfieldoption', function() {
      it('should call deleteCustomfieldsOptionsIdcustomfieldoption successfully', function(done) {
        //uncomment below and update the code to test deleteCustomfieldsOptionsIdcustomfieldoption
        //instance.deleteCustomfieldsOptionsIdcustomfieldoption(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteEnterprisesIdOrganizationsIdorg', function() {
      it('should call deleteEnterprisesIdOrganizationsIdorg successfully', function(done) {
        //uncomment below and update the code to test deleteEnterprisesIdOrganizationsIdorg
        //instance.deleteEnterprisesIdOrganizationsIdorg(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteIdIdmembersIdmember', function() {
      it('should call deleteIdIdmembersIdmember successfully', function(done) {
        //uncomment below and update the code to test deleteIdIdmembersIdmember
        //instance.deleteIdIdmembersIdmember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteLabelsId', function() {
      it('should call deleteLabelsId successfully', function(done) {
        //uncomment below and update the code to test deleteLabelsId
        //instance.deleteLabelsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteMembersIdBoardbackgroundsIdbackground', function() {
      it('should call deleteMembersIdBoardbackgroundsIdbackground successfully', function(done) {
        //uncomment below and update the code to test deleteMembersIdBoardbackgroundsIdbackground
        //instance.deleteMembersIdBoardbackgroundsIdbackground(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteMembersIdBoardstarsIdstar', function() {
      it('should call deleteMembersIdBoardstarsIdstar successfully', function(done) {
        //uncomment below and update the code to test deleteMembersIdBoardstarsIdstar
        //instance.deleteMembersIdBoardstarsIdstar(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteMembersIdCustomboardbackgroundsIdbackground', function() {
      it('should call deleteMembersIdCustomboardbackgroundsIdbackground successfully', function(done) {
        //uncomment below and update the code to test deleteMembersIdCustomboardbackgroundsIdbackground
        //instance.deleteMembersIdCustomboardbackgroundsIdbackground(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteMembersIdCustomstickersIdsticker', function() {
      it('should call deleteMembersIdCustomstickersIdsticker successfully', function(done) {
        //uncomment below and update the code to test deleteMembersIdCustomstickersIdsticker
        //instance.deleteMembersIdCustomstickersIdsticker(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteMembersIdSavedsearchesIdsearch', function() {
      it('should call deleteMembersIdSavedsearchesIdsearch successfully', function(done) {
        //uncomment below and update the code to test deleteMembersIdSavedsearchesIdsearch
        //instance.deleteMembersIdSavedsearchesIdsearch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteOrganizationsId', function() {
      it('should call deleteOrganizationsId successfully', function(done) {
        //uncomment below and update the code to test deleteOrganizationsId
        //instance.deleteOrganizationsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteOrganizationsIdLogo', function() {
      it('should call deleteOrganizationsIdLogo successfully', function(done) {
        //uncomment below and update the code to test deleteOrganizationsIdLogo
        //instance.deleteOrganizationsIdLogo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteOrganizationsIdMembers', function() {
      it('should call deleteOrganizationsIdMembers successfully', function(done) {
        //uncomment below and update the code to test deleteOrganizationsIdMembers
        //instance.deleteOrganizationsIdMembers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteOrganizationsIdPrefsAssociateddomain', function() {
      it('should call deleteOrganizationsIdPrefsAssociateddomain successfully', function(done) {
        //uncomment below and update the code to test deleteOrganizationsIdPrefsAssociateddomain
        //instance.deleteOrganizationsIdPrefsAssociateddomain(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteOrganizationsIdPrefsOrginviterestrict', function() {
      it('should call deleteOrganizationsIdPrefsOrginviterestrict successfully', function(done) {
        //uncomment below and update the code to test deleteOrganizationsIdPrefsOrginviterestrict
        //instance.deleteOrganizationsIdPrefsOrginviterestrict(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteOrganizationsIdTagsIdtag', function() {
      it('should call deleteOrganizationsIdTagsIdtag successfully', function(done) {
        //uncomment below and update the code to test deleteOrganizationsIdTagsIdtag
        //instance.deleteOrganizationsIdTagsIdtag(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteToken', function() {
      it('should call deleteToken successfully', function(done) {
        //uncomment below and update the code to test deleteToken
        //instance.deleteToken(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTokensTokenWebhooksIdwebhook', function() {
      it('should call deleteTokensTokenWebhooksIdwebhook successfully', function(done) {
        //uncomment below and update the code to test deleteTokensTokenWebhooksIdwebhook
        //instance.deleteTokensTokenWebhooksIdwebhook(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteWebhooksId', function() {
      it('should call deleteWebhooksId successfully', function(done) {
        //uncomment below and update the code to test deleteWebhooksId
        //instance.deleteWebhooksId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deletedCardsIdAttachmentsIdattachment', function() {
      it('should call deletedCardsIdAttachmentsIdattachment successfully', function(done) {
        //uncomment below and update the code to test deletedCardsIdAttachmentsIdattachment
        //instance.deletedCardsIdAttachmentsIdattachment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('emoji', function() {
      it('should call emoji successfully', function(done) {
        //uncomment below and update the code to test emoji
        //instance.emoji(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('enterprisesIdMembersIdMemberDeactivated', function() {
      it('should call enterprisesIdMembersIdMemberDeactivated successfully', function(done) {
        //uncomment below and update the code to test enterprisesIdMembersIdMemberDeactivated
        //instance.enterprisesIdMembersIdMemberDeactivated(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('enterprisesIdOrganizationsIdmember', function() {
      it('should call enterprisesIdOrganizationsIdmember successfully', function(done) {
        //uncomment below and update the code to test enterprisesIdOrganizationsIdmember
        //instance.enterprisesIdOrganizationsIdmember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActionsId', function() {
      it('should call getActionsId successfully', function(done) {
        //uncomment below and update the code to test getActionsId
        //instance.getActionsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActionsIdBoard', function() {
      it('should call getActionsIdBoard successfully', function(done) {
        //uncomment below and update the code to test getActionsIdBoard
        //instance.getActionsIdBoard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActionsIdCard', function() {
      it('should call getActionsIdCard successfully', function(done) {
        //uncomment below and update the code to test getActionsIdCard
        //instance.getActionsIdCard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActionsIdField', function() {
      it('should call getActionsIdField successfully', function(done) {
        //uncomment below and update the code to test getActionsIdField
        //instance.getActionsIdField(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActionsIdList', function() {
      it('should call getActionsIdList successfully', function(done) {
        //uncomment below and update the code to test getActionsIdList
        //instance.getActionsIdList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActionsIdMember', function() {
      it('should call getActionsIdMember successfully', function(done) {
        //uncomment below and update the code to test getActionsIdMember
        //instance.getActionsIdMember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActionsIdMembercreator', function() {
      it('should call getActionsIdMembercreator successfully', function(done) {
        //uncomment below and update the code to test getActionsIdMembercreator
        //instance.getActionsIdMembercreator(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActionsIdOrganization', function() {
      it('should call getActionsIdOrganization successfully', function(done) {
        //uncomment below and update the code to test getActionsIdOrganization
        //instance.getActionsIdOrganization(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActionsIdactionReactions', function() {
      it('should call getActionsIdactionReactions successfully', function(done) {
        //uncomment below and update the code to test getActionsIdactionReactions
        //instance.getActionsIdactionReactions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActionsIdactionReactionsId', function() {
      it('should call getActionsIdactionReactionsId successfully', function(done) {
        //uncomment below and update the code to test getActionsIdactionReactionsId
        //instance.getActionsIdactionReactionsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActionsIdactionReactionsummary', function() {
      it('should call getActionsIdactionReactionsummary successfully', function(done) {
        //uncomment below and update the code to test getActionsIdactionReactionsummary
        //instance.getActionsIdactionReactionsummary(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBatch', function() {
      it('should call getBatch successfully', function(done) {
        //uncomment below and update the code to test getBatch
        //instance.getBatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBoardIdPlugins', function() {
      it('should call getBoardIdPlugins successfully', function(done) {
        //uncomment below and update the code to test getBoardIdPlugins
        //instance.getBoardIdPlugins(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBoardsId', function() {
      it('should call getBoardsId successfully', function(done) {
        //uncomment below and update the code to test getBoardsId
        //instance.getBoardsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBoardsIdActions', function() {
      it('should call getBoardsIdActions successfully', function(done) {
        //uncomment below and update the code to test getBoardsIdActions
        //instance.getBoardsIdActions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBoardsIdBoardplugins', function() {
      it('should call getBoardsIdBoardplugins successfully', function(done) {
        //uncomment below and update the code to test getBoardsIdBoardplugins
        //instance.getBoardsIdBoardplugins(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBoardsIdBoardstars', function() {
      it('should call getBoardsIdBoardstars successfully', function(done) {
        //uncomment below and update the code to test getBoardsIdBoardstars
        //instance.getBoardsIdBoardstars(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBoardsIdCards', function() {
      it('should call getBoardsIdCards successfully', function(done) {
        //uncomment below and update the code to test getBoardsIdCards
        //instance.getBoardsIdCards(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBoardsIdCardsFilter', function() {
      it('should call getBoardsIdCardsFilter successfully', function(done) {
        //uncomment below and update the code to test getBoardsIdCardsFilter
        //instance.getBoardsIdCardsFilter(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBoardsIdCardsIdcard', function() {
      it('should call getBoardsIdCardsIdcard successfully', function(done) {
        //uncomment below and update the code to test getBoardsIdCardsIdcard
        //instance.getBoardsIdCardsIdcard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBoardsIdCustomfields', function() {
      it('should call getBoardsIdCustomfields successfully', function(done) {
        //uncomment below and update the code to test getBoardsIdCustomfields
        //instance.getBoardsIdCustomfields(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBoardsIdField', function() {
      it('should call getBoardsIdField successfully', function(done) {
        //uncomment below and update the code to test getBoardsIdField
        //instance.getBoardsIdField(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBoardsIdLabels', function() {
      it('should call getBoardsIdLabels successfully', function(done) {
        //uncomment below and update the code to test getBoardsIdLabels
        //instance.getBoardsIdLabels(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBoardsIdLists', function() {
      it('should call getBoardsIdLists successfully', function(done) {
        //uncomment below and update the code to test getBoardsIdLists
        //instance.getBoardsIdLists(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBoardsIdListsFilter', function() {
      it('should call getBoardsIdListsFilter successfully', function(done) {
        //uncomment below and update the code to test getBoardsIdListsFilter
        //instance.getBoardsIdListsFilter(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBoardsIdMembers', function() {
      it('should call getBoardsIdMembers successfully', function(done) {
        //uncomment below and update the code to test getBoardsIdMembers
        //instance.getBoardsIdMembers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBoardsIdMemberships', function() {
      it('should call getBoardsIdMemberships successfully', function(done) {
        //uncomment below and update the code to test getBoardsIdMemberships
        //instance.getBoardsIdMemberships(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCardsId', function() {
      it('should call getCardsId successfully', function(done) {
        //uncomment below and update the code to test getCardsId
        //instance.getCardsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCardsIdActions', function() {
      it('should call getCardsIdActions successfully', function(done) {
        //uncomment below and update the code to test getCardsIdActions
        //instance.getCardsIdActions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCardsIdAttachments', function() {
      it('should call getCardsIdAttachments successfully', function(done) {
        //uncomment below and update the code to test getCardsIdAttachments
        //instance.getCardsIdAttachments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCardsIdAttachmentsIdattachment', function() {
      it('should call getCardsIdAttachmentsIdattachment successfully', function(done) {
        //uncomment below and update the code to test getCardsIdAttachmentsIdattachment
        //instance.getCardsIdAttachmentsIdattachment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCardsIdBoard', function() {
      it('should call getCardsIdBoard successfully', function(done) {
        //uncomment below and update the code to test getCardsIdBoard
        //instance.getCardsIdBoard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCardsIdCheckitemIdcheckitem', function() {
      it('should call getCardsIdCheckitemIdcheckitem successfully', function(done) {
        //uncomment below and update the code to test getCardsIdCheckitemIdcheckitem
        //instance.getCardsIdCheckitemIdcheckitem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCardsIdCheckitemstates', function() {
      it('should call getCardsIdCheckitemstates successfully', function(done) {
        //uncomment below and update the code to test getCardsIdCheckitemstates
        //instance.getCardsIdCheckitemstates(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCardsIdChecklists', function() {
      it('should call getCardsIdChecklists successfully', function(done) {
        //uncomment below and update the code to test getCardsIdChecklists
        //instance.getCardsIdChecklists(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCardsIdCustomfielditems', function() {
      it('should call getCardsIdCustomfielditems successfully', function(done) {
        //uncomment below and update the code to test getCardsIdCustomfielditems
        //instance.getCardsIdCustomfielditems(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCardsIdField', function() {
      it('should call getCardsIdField successfully', function(done) {
        //uncomment below and update the code to test getCardsIdField
        //instance.getCardsIdField(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCardsIdList', function() {
      it('should call getCardsIdList successfully', function(done) {
        //uncomment below and update the code to test getCardsIdList
        //instance.getCardsIdList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCardsIdMembers', function() {
      it('should call getCardsIdMembers successfully', function(done) {
        //uncomment below and update the code to test getCardsIdMembers
        //instance.getCardsIdMembers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCardsIdMembersvoted', function() {
      it('should call getCardsIdMembersvoted successfully', function(done) {
        //uncomment below and update the code to test getCardsIdMembersvoted
        //instance.getCardsIdMembersvoted(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCardsIdPlugindata', function() {
      it('should call getCardsIdPlugindata successfully', function(done) {
        //uncomment below and update the code to test getCardsIdPlugindata
        //instance.getCardsIdPlugindata(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCardsIdStickers', function() {
      it('should call getCardsIdStickers successfully', function(done) {
        //uncomment below and update the code to test getCardsIdStickers
        //instance.getCardsIdStickers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCardsIdStickersIdsticker', function() {
      it('should call getCardsIdStickersIdsticker successfully', function(done) {
        //uncomment below and update the code to test getCardsIdStickersIdsticker
        //instance.getCardsIdStickersIdsticker(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getChecklistsId', function() {
      it('should call getChecklistsId successfully', function(done) {
        //uncomment below and update the code to test getChecklistsId
        //instance.getChecklistsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getChecklistsIdBoard', function() {
      it('should call getChecklistsIdBoard successfully', function(done) {
        //uncomment below and update the code to test getChecklistsIdBoard
        //instance.getChecklistsIdBoard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getChecklistsIdCards', function() {
      it('should call getChecklistsIdCards successfully', function(done) {
        //uncomment below and update the code to test getChecklistsIdCards
        //instance.getChecklistsIdCards(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getChecklistsIdCheckitems', function() {
      it('should call getChecklistsIdCheckitems successfully', function(done) {
        //uncomment below and update the code to test getChecklistsIdCheckitems
        //instance.getChecklistsIdCheckitems(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getChecklistsIdCheckitemsIdcheckitem', function() {
      it('should call getChecklistsIdCheckitemsIdcheckitem successfully', function(done) {
        //uncomment below and update the code to test getChecklistsIdCheckitemsIdcheckitem
        //instance.getChecklistsIdCheckitemsIdcheckitem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getChecklistsIdField', function() {
      it('should call getChecklistsIdField successfully', function(done) {
        //uncomment below and update the code to test getChecklistsIdField
        //instance.getChecklistsIdField(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCustomfieldsId', function() {
      it('should call getCustomfieldsId successfully', function(done) {
        //uncomment below and update the code to test getCustomfieldsId
        //instance.getCustomfieldsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCustomfieldsIdOptions', function() {
      it('should call getCustomfieldsIdOptions successfully', function(done) {
        //uncomment below and update the code to test getCustomfieldsIdOptions
        //instance.getCustomfieldsIdOptions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCustomfieldsOptionsIdcustomfieldoption', function() {
      it('should call getCustomfieldsOptionsIdcustomfieldoption successfully', function(done) {
        //uncomment below and update the code to test getCustomfieldsOptionsIdcustomfieldoption
        //instance.getCustomfieldsOptionsIdcustomfieldoption(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEnterprisesId', function() {
      it('should call getEnterprisesId successfully', function(done) {
        //uncomment below and update the code to test getEnterprisesId
        //instance.getEnterprisesId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEnterprisesIdAdmins', function() {
      it('should call getEnterprisesIdAdmins successfully', function(done) {
        //uncomment below and update the code to test getEnterprisesIdAdmins
        //instance.getEnterprisesIdAdmins(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEnterprisesIdAuditlog', function() {
      it('should call getEnterprisesIdAuditlog successfully', function(done) {
        //uncomment below and update the code to test getEnterprisesIdAuditlog
        //instance.getEnterprisesIdAuditlog(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEnterprisesIdMembers', function() {
      it('should call getEnterprisesIdMembers successfully', function(done) {
        //uncomment below and update the code to test getEnterprisesIdMembers
        //instance.getEnterprisesIdMembers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEnterprisesIdMembersIdmember', function() {
      it('should call getEnterprisesIdMembersIdmember successfully', function(done) {
        //uncomment below and update the code to test getEnterprisesIdMembersIdmember
        //instance.getEnterprisesIdMembersIdmember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEnterprisesIdSignupurl', function() {
      it('should call getEnterprisesIdSignupurl successfully', function(done) {
        //uncomment below and update the code to test getEnterprisesIdSignupurl
        //instance.getEnterprisesIdSignupurl(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEnterprisesIdTransferrableOrganizationIdOrganization', function() {
      it('should call getEnterprisesIdTransferrableOrganizationIdOrganization successfully', function(done) {
        //uncomment below and update the code to test getEnterprisesIdTransferrableOrganizationIdOrganization
        //instance.getEnterprisesIdTransferrableOrganizationIdOrganization(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLabelsId', function() {
      it('should call getLabelsId successfully', function(done) {
        //uncomment below and update the code to test getLabelsId
        //instance.getLabelsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getListsId', function() {
      it('should call getListsId successfully', function(done) {
        //uncomment below and update the code to test getListsId
        //instance.getListsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getListsIdActions', function() {
      it('should call getListsIdActions successfully', function(done) {
        //uncomment below and update the code to test getListsIdActions
        //instance.getListsIdActions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getListsIdBoard', function() {
      it('should call getListsIdBoard successfully', function(done) {
        //uncomment below and update the code to test getListsIdBoard
        //instance.getListsIdBoard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getListsIdCards', function() {
      it('should call getListsIdCards successfully', function(done) {
        //uncomment below and update the code to test getListsIdCards
        //instance.getListsIdCards(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdActions', function() {
      it('should call getMembersIdActions successfully', function(done) {
        //uncomment below and update the code to test getMembersIdActions
        //instance.getMembersIdActions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdBoardbackgrounds', function() {
      it('should call getMembersIdBoardbackgrounds successfully', function(done) {
        //uncomment below and update the code to test getMembersIdBoardbackgrounds
        //instance.getMembersIdBoardbackgrounds(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdBoardbackgroundsIdbackground', function() {
      it('should call getMembersIdBoardbackgroundsIdbackground successfully', function(done) {
        //uncomment below and update the code to test getMembersIdBoardbackgroundsIdbackground
        //instance.getMembersIdBoardbackgroundsIdbackground(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdBoards', function() {
      it('should call getMembersIdBoards successfully', function(done) {
        //uncomment below and update the code to test getMembersIdBoards
        //instance.getMembersIdBoards(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdBoardsinvited', function() {
      it('should call getMembersIdBoardsinvited successfully', function(done) {
        //uncomment below and update the code to test getMembersIdBoardsinvited
        //instance.getMembersIdBoardsinvited(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdBoardstars', function() {
      it('should call getMembersIdBoardstars successfully', function(done) {
        //uncomment below and update the code to test getMembersIdBoardstars
        //instance.getMembersIdBoardstars(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdBoardstarsIdstar', function() {
      it('should call getMembersIdBoardstarsIdstar successfully', function(done) {
        //uncomment below and update the code to test getMembersIdBoardstarsIdstar
        //instance.getMembersIdBoardstarsIdstar(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdCards', function() {
      it('should call getMembersIdCards successfully', function(done) {
        //uncomment below and update the code to test getMembersIdCards
        //instance.getMembersIdCards(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdCustomboardbackgrounds', function() {
      it('should call getMembersIdCustomboardbackgrounds successfully', function(done) {
        //uncomment below and update the code to test getMembersIdCustomboardbackgrounds
        //instance.getMembersIdCustomboardbackgrounds(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdCustomboardbackgroundsIdbackground', function() {
      it('should call getMembersIdCustomboardbackgroundsIdbackground successfully', function(done) {
        //uncomment below and update the code to test getMembersIdCustomboardbackgroundsIdbackground
        //instance.getMembersIdCustomboardbackgroundsIdbackground(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdCustomemoji', function() {
      it('should call getMembersIdCustomemoji successfully', function(done) {
        //uncomment below and update the code to test getMembersIdCustomemoji
        //instance.getMembersIdCustomemoji(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdCustomstickers', function() {
      it('should call getMembersIdCustomstickers successfully', function(done) {
        //uncomment below and update the code to test getMembersIdCustomstickers
        //instance.getMembersIdCustomstickers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdCustomstickersIdsticker', function() {
      it('should call getMembersIdCustomstickersIdsticker successfully', function(done) {
        //uncomment below and update the code to test getMembersIdCustomstickersIdsticker
        //instance.getMembersIdCustomstickersIdsticker(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdField', function() {
      it('should call getMembersIdField successfully', function(done) {
        //uncomment below and update the code to test getMembersIdField
        //instance.getMembersIdField(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdNotifications', function() {
      it('should call getMembersIdNotifications successfully', function(done) {
        //uncomment below and update the code to test getMembersIdNotifications
        //instance.getMembersIdNotifications(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdOrganizations', function() {
      it('should call getMembersIdOrganizations successfully', function(done) {
        //uncomment below and update the code to test getMembersIdOrganizations
        //instance.getMembersIdOrganizations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdOrganizationsinvited', function() {
      it('should call getMembersIdOrganizationsinvited successfully', function(done) {
        //uncomment below and update the code to test getMembersIdOrganizationsinvited
        //instance.getMembersIdOrganizationsinvited(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdSavedsearches', function() {
      it('should call getMembersIdSavedsearches successfully', function(done) {
        //uncomment below and update the code to test getMembersIdSavedsearches
        //instance.getMembersIdSavedsearches(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdSavedsearchesIdsearch', function() {
      it('should call getMembersIdSavedsearchesIdsearch successfully', function(done) {
        //uncomment below and update the code to test getMembersIdSavedsearchesIdsearch
        //instance.getMembersIdSavedsearchesIdsearch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersIdTokens', function() {
      it('should call getMembersIdTokens successfully', function(done) {
        //uncomment below and update the code to test getMembersIdTokens
        //instance.getMembersIdTokens(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembersid', function() {
      it('should call getMembersid successfully', function(done) {
        //uncomment below and update the code to test getMembersid
        //instance.getMembersid(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNotificationsId', function() {
      it('should call getNotificationsId successfully', function(done) {
        //uncomment below and update the code to test getNotificationsId
        //instance.getNotificationsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNotificationsIdBoard', function() {
      it('should call getNotificationsIdBoard successfully', function(done) {
        //uncomment below and update the code to test getNotificationsIdBoard
        //instance.getNotificationsIdBoard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNotificationsIdCard', function() {
      it('should call getNotificationsIdCard successfully', function(done) {
        //uncomment below and update the code to test getNotificationsIdCard
        //instance.getNotificationsIdCard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNotificationsIdField', function() {
      it('should call getNotificationsIdField successfully', function(done) {
        //uncomment below and update the code to test getNotificationsIdField
        //instance.getNotificationsIdField(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNotificationsIdList', function() {
      it('should call getNotificationsIdList successfully', function(done) {
        //uncomment below and update the code to test getNotificationsIdList
        //instance.getNotificationsIdList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNotificationsIdMembercreator', function() {
      it('should call getNotificationsIdMembercreator successfully', function(done) {
        //uncomment below and update the code to test getNotificationsIdMembercreator
        //instance.getNotificationsIdMembercreator(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNotificationsIdOrganization', function() {
      it('should call getNotificationsIdOrganization successfully', function(done) {
        //uncomment below and update the code to test getNotificationsIdOrganization
        //instance.getNotificationsIdOrganization(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrganizationsId', function() {
      it('should call getOrganizationsId successfully', function(done) {
        //uncomment below and update the code to test getOrganizationsId
        //instance.getOrganizationsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrganizationsIdActions', function() {
      it('should call getOrganizationsIdActions successfully', function(done) {
        //uncomment below and update the code to test getOrganizationsIdActions
        //instance.getOrganizationsIdActions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrganizationsIdBoards', function() {
      it('should call getOrganizationsIdBoards successfully', function(done) {
        //uncomment below and update the code to test getOrganizationsIdBoards
        //instance.getOrganizationsIdBoards(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrganizationsIdExports', function() {
      it('should call getOrganizationsIdExports successfully', function(done) {
        //uncomment below and update the code to test getOrganizationsIdExports
        //instance.getOrganizationsIdExports(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrganizationsIdField', function() {
      it('should call getOrganizationsIdField successfully', function(done) {
        //uncomment below and update the code to test getOrganizationsIdField
        //instance.getOrganizationsIdField(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrganizationsIdMembers', function() {
      it('should call getOrganizationsIdMembers successfully', function(done) {
        //uncomment below and update the code to test getOrganizationsIdMembers
        //instance.getOrganizationsIdMembers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrganizationsIdMemberships', function() {
      it('should call getOrganizationsIdMemberships successfully', function(done) {
        //uncomment below and update the code to test getOrganizationsIdMemberships
        //instance.getOrganizationsIdMemberships(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrganizationsIdMembershipsIdmembership', function() {
      it('should call getOrganizationsIdMembershipsIdmembership successfully', function(done) {
        //uncomment below and update the code to test getOrganizationsIdMembershipsIdmembership
        //instance.getOrganizationsIdMembershipsIdmembership(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrganizationsIdNewbillableguestsIdboard', function() {
      it('should call getOrganizationsIdNewbillableguestsIdboard successfully', function(done) {
        //uncomment below and update the code to test getOrganizationsIdNewbillableguestsIdboard
        //instance.getOrganizationsIdNewbillableguestsIdboard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrganizationsIdPlugindata', function() {
      it('should call getOrganizationsIdPlugindata successfully', function(done) {
        //uncomment below and update the code to test getOrganizationsIdPlugindata
        //instance.getOrganizationsIdPlugindata(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrganizationsIdTags', function() {
      it('should call getOrganizationsIdTags successfully', function(done) {
        //uncomment below and update the code to test getOrganizationsIdTags
        //instance.getOrganizationsIdTags(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPluginsId', function() {
      it('should call getPluginsId successfully', function(done) {
        //uncomment below and update the code to test getPluginsId
        //instance.getPluginsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPluginsIdComplianceMemberprivacy', function() {
      it('should call getPluginsIdComplianceMemberprivacy successfully', function(done) {
        //uncomment below and update the code to test getPluginsIdComplianceMemberprivacy
        //instance.getPluginsIdComplianceMemberprivacy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSearch', function() {
      it('should call getSearch successfully', function(done) {
        //uncomment below and update the code to test getSearch
        //instance.getSearch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSearchMembers', function() {
      it('should call getSearchMembers successfully', function(done) {
        //uncomment below and update the code to test getSearchMembers
        //instance.getSearchMembers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTokensToken', function() {
      it('should call getTokensToken successfully', function(done) {
        //uncomment below and update the code to test getTokensToken
        //instance.getTokensToken(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTokensTokenMember', function() {
      it('should call getTokensTokenMember successfully', function(done) {
        //uncomment below and update the code to test getTokensTokenMember
        //instance.getTokensTokenMember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTokensTokenWebhooks', function() {
      it('should call getTokensTokenWebhooks successfully', function(done) {
        //uncomment below and update the code to test getTokensTokenWebhooks
        //instance.getTokensTokenWebhooks(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTokensTokenWebhooksIdwebhook', function() {
      it('should call getTokensTokenWebhooksIdwebhook successfully', function(done) {
        //uncomment below and update the code to test getTokensTokenWebhooksIdwebhook
        //instance.getTokensTokenWebhooksIdwebhook(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getWebhooksId', function() {
      it('should call getWebhooksId successfully', function(done) {
        //uncomment below and update the code to test getWebhooksId
        //instance.getWebhooksId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('membersidavatar', function() {
      it('should call membersidavatar successfully', function(done) {
        //uncomment below and update the code to test membersidavatar
        //instance.membersidavatar(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('membersidcustomboardbackgrounds1', function() {
      it('should call membersidcustomboardbackgrounds1 successfully', function(done) {
        //uncomment below and update the code to test membersidcustomboardbackgrounds1
        //instance.membersidcustomboardbackgrounds1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('membersidcustomemojiidemoji', function() {
      it('should call membersidcustomemojiidemoji successfully', function(done) {
        //uncomment below and update the code to test membersidcustomemojiidemoji
        //instance.membersidcustomemojiidemoji(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('notificationsidmember', function() {
      it('should call notificationsidmember successfully', function(done) {
        //uncomment below and update the code to test notificationsidmember
        //instance.notificationsidmember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('organizationsIdMembersIdmemberAll', function() {
      it('should call organizationsIdMembersIdmemberAll successfully', function(done) {
        //uncomment below and update the code to test organizationsIdMembersIdmemberAll
        //instance.organizationsIdMembersIdmemberAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postActionsIdactionReactions', function() {
      it('should call postActionsIdactionReactions successfully', function(done) {
        //uncomment below and update the code to test postActionsIdactionReactions
        //instance.postActionsIdactionReactions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postBoards', function() {
      it('should call postBoards successfully', function(done) {
        //uncomment below and update the code to test postBoards
        //instance.postBoards(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postBoardsIdBoardplugins', function() {
      it('should call postBoardsIdBoardplugins successfully', function(done) {
        //uncomment below and update the code to test postBoardsIdBoardplugins
        //instance.postBoardsIdBoardplugins(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postBoardsIdCalendarkeyGenerate', function() {
      it('should call postBoardsIdCalendarkeyGenerate successfully', function(done) {
        //uncomment below and update the code to test postBoardsIdCalendarkeyGenerate
        //instance.postBoardsIdCalendarkeyGenerate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postBoardsIdChecklists', function() {
      it('should call postBoardsIdChecklists successfully', function(done) {
        //uncomment below and update the code to test postBoardsIdChecklists
        //instance.postBoardsIdChecklists(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postBoardsIdEmailkeyGenerate', function() {
      it('should call postBoardsIdEmailkeyGenerate successfully', function(done) {
        //uncomment below and update the code to test postBoardsIdEmailkeyGenerate
        //instance.postBoardsIdEmailkeyGenerate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postBoardsIdIdtags', function() {
      it('should call postBoardsIdIdtags successfully', function(done) {
        //uncomment below and update the code to test postBoardsIdIdtags
        //instance.postBoardsIdIdtags(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postBoardsIdLabels', function() {
      it('should call postBoardsIdLabels successfully', function(done) {
        //uncomment below and update the code to test postBoardsIdLabels
        //instance.postBoardsIdLabels(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postBoardsIdLists', function() {
      it('should call postBoardsIdLists successfully', function(done) {
        //uncomment below and update the code to test postBoardsIdLists
        //instance.postBoardsIdLists(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postBoardsIdMarkedasviewed', function() {
      it('should call postBoardsIdMarkedasviewed successfully', function(done) {
        //uncomment below and update the code to test postBoardsIdMarkedasviewed
        //instance.postBoardsIdMarkedasviewed(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postBoardsIdPowerups', function() {
      it('should call postBoardsIdPowerups successfully', function(done) {
        //uncomment below and update the code to test postBoardsIdPowerups
        //instance.postBoardsIdPowerups(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCards', function() {
      it('should call postCards successfully', function(done) {
        //uncomment below and update the code to test postCards
        //instance.postCards(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCardsIdActionsComments', function() {
      it('should call postCardsIdActionsComments successfully', function(done) {
        //uncomment below and update the code to test postCardsIdActionsComments
        //instance.postCardsIdActionsComments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCardsIdAttachments', function() {
      it('should call postCardsIdAttachments successfully', function(done) {
        //uncomment below and update the code to test postCardsIdAttachments
        //instance.postCardsIdAttachments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCardsIdChecklists', function() {
      it('should call postCardsIdChecklists successfully', function(done) {
        //uncomment below and update the code to test postCardsIdChecklists
        //instance.postCardsIdChecklists(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCardsIdIdlabels', function() {
      it('should call postCardsIdIdlabels successfully', function(done) {
        //uncomment below and update the code to test postCardsIdIdlabels
        //instance.postCardsIdIdlabels(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCardsIdIdmembers', function() {
      it('should call postCardsIdIdmembers successfully', function(done) {
        //uncomment below and update the code to test postCardsIdIdmembers
        //instance.postCardsIdIdmembers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCardsIdLabels', function() {
      it('should call postCardsIdLabels successfully', function(done) {
        //uncomment below and update the code to test postCardsIdLabels
        //instance.postCardsIdLabels(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCardsIdMarkassociatednotificationsread', function() {
      it('should call postCardsIdMarkassociatednotificationsread successfully', function(done) {
        //uncomment below and update the code to test postCardsIdMarkassociatednotificationsread
        //instance.postCardsIdMarkassociatednotificationsread(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCardsIdStickers', function() {
      it('should call postCardsIdStickers successfully', function(done) {
        //uncomment below and update the code to test postCardsIdStickers
        //instance.postCardsIdStickers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postChecklists', function() {
      it('should call postChecklists successfully', function(done) {
        //uncomment below and update the code to test postChecklists
        //instance.postChecklists(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postChecklistsIdCheckitems', function() {
      it('should call postChecklistsIdCheckitems successfully', function(done) {
        //uncomment below and update the code to test postChecklistsIdCheckitems
        //instance.postChecklistsIdCheckitems(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCustomfields', function() {
      it('should call postCustomfields successfully', function(done) {
        //uncomment below and update the code to test postCustomfields
        //instance.postCustomfields(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCustomfieldsIdOptions', function() {
      it('should call postCustomfieldsIdOptions successfully', function(done) {
        //uncomment below and update the code to test postCustomfieldsIdOptions
        //instance.postCustomfieldsIdOptions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postEnterprisesIdTokens', function() {
      it('should call postEnterprisesIdTokens successfully', function(done) {
        //uncomment below and update the code to test postEnterprisesIdTokens
        //instance.postEnterprisesIdTokens(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postLabels', function() {
      it('should call postLabels successfully', function(done) {
        //uncomment below and update the code to test postLabels
        //instance.postLabels(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postLists', function() {
      it('should call postLists successfully', function(done) {
        //uncomment below and update the code to test postLists
        //instance.postLists(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postListsIdArchiveallcards', function() {
      it('should call postListsIdArchiveallcards successfully', function(done) {
        //uncomment below and update the code to test postListsIdArchiveallcards
        //instance.postListsIdArchiveallcards(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postListsIdMoveallcards', function() {
      it('should call postListsIdMoveallcards successfully', function(done) {
        //uncomment below and update the code to test postListsIdMoveallcards
        //instance.postListsIdMoveallcards(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postMembersIdBoardbackgrounds1', function() {
      it('should call postMembersIdBoardbackgrounds1 successfully', function(done) {
        //uncomment below and update the code to test postMembersIdBoardbackgrounds1
        //instance.postMembersIdBoardbackgrounds1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postMembersIdBoardstars', function() {
      it('should call postMembersIdBoardstars successfully', function(done) {
        //uncomment below and update the code to test postMembersIdBoardstars
        //instance.postMembersIdBoardstars(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postMembersIdCustomemoji', function() {
      it('should call postMembersIdCustomemoji successfully', function(done) {
        //uncomment below and update the code to test postMembersIdCustomemoji
        //instance.postMembersIdCustomemoji(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postMembersIdCustomstickers', function() {
      it('should call postMembersIdCustomstickers successfully', function(done) {
        //uncomment below and update the code to test postMembersIdCustomstickers
        //instance.postMembersIdCustomstickers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postMembersIdOnetimemessagesdismissed', function() {
      it('should call postMembersIdOnetimemessagesdismissed successfully', function(done) {
        //uncomment below and update the code to test postMembersIdOnetimemessagesdismissed
        //instance.postMembersIdOnetimemessagesdismissed(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postMembersIdSavedsearches', function() {
      it('should call postMembersIdSavedsearches successfully', function(done) {
        //uncomment below and update the code to test postMembersIdSavedsearches
        //instance.postMembersIdSavedsearches(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postNotificationsAllRead', function() {
      it('should call postNotificationsAllRead successfully', function(done) {
        //uncomment below and update the code to test postNotificationsAllRead
        //instance.postNotificationsAllRead(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postOrganizations', function() {
      it('should call postOrganizations successfully', function(done) {
        //uncomment below and update the code to test postOrganizations
        //instance.postOrganizations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postOrganizationsIdExports', function() {
      it('should call postOrganizationsIdExports successfully', function(done) {
        //uncomment below and update the code to test postOrganizationsIdExports
        //instance.postOrganizationsIdExports(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postOrganizationsIdLogo', function() {
      it('should call postOrganizationsIdLogo successfully', function(done) {
        //uncomment below and update the code to test postOrganizationsIdLogo
        //instance.postOrganizationsIdLogo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postOrganizationsIdTags', function() {
      it('should call postOrganizationsIdTags successfully', function(done) {
        //uncomment below and update the code to test postOrganizationsIdTags
        //instance.postOrganizationsIdTags(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postPluginsIdpluginListing', function() {
      it('should call postPluginsIdpluginListing successfully', function(done) {
        //uncomment below and update the code to test postPluginsIdpluginListing
        //instance.postPluginsIdpluginListing(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postTokensTokenWebhooks', function() {
      it('should call postTokensTokenWebhooks successfully', function(done) {
        //uncomment below and update the code to test postTokensTokenWebhooks
        //instance.postTokensTokenWebhooks(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postWebhooks', function() {
      it('should call postWebhooks successfully', function(done) {
        //uncomment below and update the code to test postWebhooks
        //instance.postWebhooks(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putActionsId', function() {
      it('should call putActionsId successfully', function(done) {
        //uncomment below and update the code to test putActionsId
        //instance.putActionsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putActionsIdText', function() {
      it('should call putActionsIdText successfully', function(done) {
        //uncomment below and update the code to test putActionsIdText
        //instance.putActionsIdText(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putBoardsId', function() {
      it('should call putBoardsId successfully', function(done) {
        //uncomment below and update the code to test putBoardsId
        //instance.putBoardsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putBoardsIdMembers', function() {
      it('should call putBoardsIdMembers successfully', function(done) {
        //uncomment below and update the code to test putBoardsIdMembers
        //instance.putBoardsIdMembers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putBoardsIdMembersIdmember', function() {
      it('should call putBoardsIdMembersIdmember successfully', function(done) {
        //uncomment below and update the code to test putBoardsIdMembersIdmember
        //instance.putBoardsIdMembersIdmember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putBoardsIdMembershipsIdmembership', function() {
      it('should call putBoardsIdMembershipsIdmembership successfully', function(done) {
        //uncomment below and update the code to test putBoardsIdMembershipsIdmembership
        //instance.putBoardsIdMembershipsIdmembership(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putBoardsIdMyPrefsShowlistguide', function() {
      it('should call putBoardsIdMyPrefsShowlistguide successfully', function(done) {
        //uncomment below and update the code to test putBoardsIdMyPrefsShowlistguide
        //instance.putBoardsIdMyPrefsShowlistguide(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putBoardsIdMyPrefsShowsidebar', function() {
      it('should call putBoardsIdMyPrefsShowsidebar successfully', function(done) {
        //uncomment below and update the code to test putBoardsIdMyPrefsShowsidebar
        //instance.putBoardsIdMyPrefsShowsidebar(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putBoardsIdMyPrefsShowsidebaractivity', function() {
      it('should call putBoardsIdMyPrefsShowsidebaractivity successfully', function(done) {
        //uncomment below and update the code to test putBoardsIdMyPrefsShowsidebaractivity
        //instance.putBoardsIdMyPrefsShowsidebaractivity(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putBoardsIdMyPrefsShowsidebarboardactions', function() {
      it('should call putBoardsIdMyPrefsShowsidebarboardactions successfully', function(done) {
        //uncomment below and update the code to test putBoardsIdMyPrefsShowsidebarboardactions
        //instance.putBoardsIdMyPrefsShowsidebarboardactions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putBoardsIdMyPrefsShowsidebarmembers', function() {
      it('should call putBoardsIdMyPrefsShowsidebarmembers successfully', function(done) {
        //uncomment below and update the code to test putBoardsIdMyPrefsShowsidebarmembers
        //instance.putBoardsIdMyPrefsShowsidebarmembers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putBoardsIdMyprefsEmailposition', function() {
      it('should call putBoardsIdMyprefsEmailposition successfully', function(done) {
        //uncomment below and update the code to test putBoardsIdMyprefsEmailposition
        //instance.putBoardsIdMyprefsEmailposition(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putBoardsIdMyprefsIdemaillist', function() {
      it('should call putBoardsIdMyprefsIdemaillist successfully', function(done) {
        //uncomment below and update the code to test putBoardsIdMyprefsIdemaillist
        //instance.putBoardsIdMyprefsIdemaillist(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putCardsId', function() {
      it('should call putCardsId successfully', function(done) {
        //uncomment below and update the code to test putCardsId
        //instance.putCardsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putCardsIdActionsIdactionComments', function() {
      it('should call putCardsIdActionsIdactionComments successfully', function(done) {
        //uncomment below and update the code to test putCardsIdActionsIdactionComments
        //instance.putCardsIdActionsIdactionComments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putCardsIdCheckitemIdcheckitem', function() {
      it('should call putCardsIdCheckitemIdcheckitem successfully', function(done) {
        //uncomment below and update the code to test putCardsIdCheckitemIdcheckitem
        //instance.putCardsIdCheckitemIdcheckitem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putCardsIdStickersIdsticker', function() {
      it('should call putCardsIdStickersIdsticker successfully', function(done) {
        //uncomment below and update the code to test putCardsIdStickersIdsticker
        //instance.putCardsIdStickersIdsticker(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putCardsIdcardChecklistIdchecklistCheckitemIdcheckitem', function() {
      it('should call putCardsIdcardChecklistIdchecklistCheckitemIdcheckitem successfully', function(done) {
        //uncomment below and update the code to test putCardsIdcardChecklistIdchecklistCheckitemIdcheckitem
        //instance.putCardsIdcardChecklistIdchecklistCheckitemIdcheckitem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putCardsIdcardCustomfieldIdcustomfieldItem', function() {
      it('should call putCardsIdcardCustomfieldIdcustomfieldItem successfully', function(done) {
        //uncomment below and update the code to test putCardsIdcardCustomfieldIdcustomfieldItem
        //instance.putCardsIdcardCustomfieldIdcustomfieldItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putChecklistsIdField', function() {
      it('should call putChecklistsIdField successfully', function(done) {
        //uncomment below and update the code to test putChecklistsIdField
        //instance.putChecklistsIdField(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putCheclistsId', function() {
      it('should call putCheclistsId successfully', function(done) {
        //uncomment below and update the code to test putCheclistsId
        //instance.putCheclistsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putCustomfieldsId', function() {
      it('should call putCustomfieldsId successfully', function(done) {
        //uncomment below and update the code to test putCustomfieldsId
        //instance.putCustomfieldsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putEnterprisesIdAdminsIdmember', function() {
      it('should call putEnterprisesIdAdminsIdmember successfully', function(done) {
        //uncomment below and update the code to test putEnterprisesIdAdminsIdmember
        //instance.putEnterprisesIdAdminsIdmember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putEnterprisesIdMembersIdmemberLicensed', function() {
      it('should call putEnterprisesIdMembersIdmemberLicensed successfully', function(done) {
        //uncomment below and update the code to test putEnterprisesIdMembersIdmemberLicensed
        //instance.putEnterprisesIdMembersIdmemberLicensed(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putEnterprisesIdOrganizations', function() {
      it('should call putEnterprisesIdOrganizations successfully', function(done) {
        //uncomment below and update the code to test putEnterprisesIdOrganizations
        //instance.putEnterprisesIdOrganizations(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putIdIdboard', function() {
      it('should call putIdIdboard successfully', function(done) {
        //uncomment below and update the code to test putIdIdboard
        //instance.putIdIdboard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putLabelsId', function() {
      it('should call putLabelsId successfully', function(done) {
        //uncomment below and update the code to test putLabelsId
        //instance.putLabelsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putLabelsIdField', function() {
      it('should call putLabelsIdField successfully', function(done) {
        //uncomment below and update the code to test putLabelsIdField
        //instance.putLabelsIdField(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putListsId', function() {
      it('should call putListsId successfully', function(done) {
        //uncomment below and update the code to test putListsId
        //instance.putListsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putListsIdClosed', function() {
      it('should call putListsIdClosed successfully', function(done) {
        //uncomment below and update the code to test putListsIdClosed
        //instance.putListsIdClosed(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putListsIdField', function() {
      it('should call putListsIdField successfully', function(done) {
        //uncomment below and update the code to test putListsIdField
        //instance.putListsIdField(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putMembersId', function() {
      it('should call putMembersId successfully', function(done) {
        //uncomment below and update the code to test putMembersId
        //instance.putMembersId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putMembersIdBoardbackgroundsIdbackground', function() {
      it('should call putMembersIdBoardbackgroundsIdbackground successfully', function(done) {
        //uncomment below and update the code to test putMembersIdBoardbackgroundsIdbackground
        //instance.putMembersIdBoardbackgroundsIdbackground(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putMembersIdBoardstarsIdstar', function() {
      it('should call putMembersIdBoardstarsIdstar successfully', function(done) {
        //uncomment below and update the code to test putMembersIdBoardstarsIdstar
        //instance.putMembersIdBoardstarsIdstar(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putMembersIdCustomboardbackgroundsIdbackground', function() {
      it('should call putMembersIdCustomboardbackgroundsIdbackground successfully', function(done) {
        //uncomment below and update the code to test putMembersIdCustomboardbackgroundsIdbackground
        //instance.putMembersIdCustomboardbackgroundsIdbackground(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putMembersIdSavedsearchesIdsearch', function() {
      it('should call putMembersIdSavedsearchesIdsearch successfully', function(done) {
        //uncomment below and update the code to test putMembersIdSavedsearchesIdsearch
        //instance.putMembersIdSavedsearchesIdsearch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putNotificationsId', function() {
      it('should call putNotificationsId successfully', function(done) {
        //uncomment below and update the code to test putNotificationsId
        //instance.putNotificationsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putNotificationsIdUnread', function() {
      it('should call putNotificationsIdUnread successfully', function(done) {
        //uncomment below and update the code to test putNotificationsIdUnread
        //instance.putNotificationsIdUnread(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putOrganizationsId', function() {
      it('should call putOrganizationsId successfully', function(done) {
        //uncomment below and update the code to test putOrganizationsId
        //instance.putOrganizationsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putOrganizationsIdMembers', function() {
      it('should call putOrganizationsIdMembers successfully', function(done) {
        //uncomment below and update the code to test putOrganizationsIdMembers
        //instance.putOrganizationsIdMembers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putOrganizationsIdMembersIdmember', function() {
      it('should call putOrganizationsIdMembersIdmember successfully', function(done) {
        //uncomment below and update the code to test putOrganizationsIdMembersIdmember
        //instance.putOrganizationsIdMembersIdmember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putOrganizationsIdMembersIdmemberDeactivated', function() {
      it('should call putOrganizationsIdMembersIdmemberDeactivated successfully', function(done) {
        //uncomment below and update the code to test putOrganizationsIdMembersIdmemberDeactivated
        //instance.putOrganizationsIdMembersIdmemberDeactivated(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putPluginsId', function() {
      it('should call putPluginsId successfully', function(done) {
        //uncomment below and update the code to test putPluginsId
        //instance.putPluginsId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putPluginsIdpluginListingsIdlisting', function() {
      it('should call putPluginsIdpluginListingsIdlisting successfully', function(done) {
        //uncomment below and update the code to test putPluginsIdpluginListingsIdlisting
        //instance.putPluginsIdpluginListingsIdlisting(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putWebhooksId', function() {
      it('should call putWebhooksId successfully', function(done) {
        //uncomment below and update the code to test putWebhooksId
        //instance.putWebhooksId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tokenstokenwebhooks1', function() {
      it('should call tokenstokenwebhooks1 successfully', function(done) {
        //uncomment below and update the code to test tokenstokenwebhooks1
        //instance.tokenstokenwebhooks1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('webhooksidfield', function() {
      it('should call webhooksidfield successfully', function(done) {
        //uncomment below and update the code to test webhooksidfield
        //instance.webhooksidfield(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
